//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_mstr
    {
        public string ac_code { get; set; }
        public Nullable<int> ac_fpos { get; set; }
        public string ac_type { get; set; }
        public string ac_desc { get; set; }
        public Nullable<bool> ac_active { get; set; }
    }
}
