//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class acd_det
    {
        public string acd_acc { get; set; }
        public string acd_cc { get; set; }
        public string acd_entity { get; set; }
        public string acd_project { get; set; }
        public int acd_year { get; set; }
        public int acd_per { get; set; }
        public decimal acd_amt { get; set; }
        public decimal acd_curr_amt { get; set; }
        public string acd_sub { get; set; }
        public decimal acd_dr_amt { get; set; }
        public decimal acd_cr_amt { get; set; }
    }
}
