//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_mstr_manual
    {
        public string ad_addr { get; set; }
        public string ad_name { get; set; }
        public string ad_line1 { get; set; }
        public string ad_line2 { get; set; }
        public string ad_city { get; set; }
        public string ad_state { get; set; }
        public string ad_zip { get; set; }
        public string ad_type { get; set; }
        public string ad_attn { get; set; }
        public string ad_phone { get; set; }
        public string ad_ext { get; set; }
        public string ad_ref { get; set; }
        public string ad_country { get; set; }
        public string ad_attn2 { get; set; }
        public string ad_phone2 { get; set; }
        public string ad_ext2 { get; set; }
        public string ad_fax { get; set; }
        public string ad_fax2 { get; set; }
        public string ad_line3 { get; set; }
        public Nullable<System.DateTime> ad_date { get; set; }
        public string ad_county { get; set; }
        public string ad_ctry { get; set; }
        public string PartnerCode { get; set; }
        public string PartnerDesc { get; set; }
        public string PartnerSubCode { get; set; }
        public string RegionCode { get; set; }
        public string State { get; set; }
        public string Zone { get; set; }
        public string DistributionCentre { get; set; }
        public string CslReportingGroup { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
    }
}
