//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_mstr_extra
    {
        public string ad_addr { get; set; }
        public string PartnerCode { get; set; }
        public string PartnerDesc { get; set; }
        public string PartnerSubCode { get; set; }
        public string PartnerSubDesc { get; set; }
        public string RegionCode { get; set; }
        public string State { get; set; }
        public string Zone { get; set; }
        public string DistributionCentre { get; set; }
        public string CslReportingGroup { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public int EntityId { get; set; }
        public string CslUploadRule { get; set; }
    }
}
