//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ap_mstr
    {
        public string ap_type { get; set; }
        public string ap_ref { get; set; }
        public string ap_batch { get; set; }
        public string ap_vend { get; set; }
        public Nullable<System.DateTime> ap_effdate { get; set; }
        public Nullable<System.DateTime> ap_date { get; set; }
        public Nullable<decimal> ap_amt { get; set; }
        public string ap_acct { get; set; }
        public string ap_cc { get; set; }
        public string ap_disc_acct { get; set; }
        public string ap_disc_cc { get; set; }
        public Nullable<bool> ap_open { get; set; }
        public string ap_rmk { get; set; }
        public string ap_user1 { get; set; }
        public string ap_user2 { get; set; }
        public string ap_curr { get; set; }
        public Nullable<decimal> ap_ex_rate { get; set; }
        public string ap_bank { get; set; }
        public string ap_sort { get; set; }
        public Nullable<System.DateTime> ap_expt_date { get; set; }
        public string ap_entity { get; set; }
        public Nullable<decimal> ap_ent_ex { get; set; }
        public string ap_ckfrm { get; set; }
        public string ap__qad01 { get; set; }
        public string ap__qad02 { get; set; }
        public Nullable<bool> ap__qad03 { get; set; }
        public string ap_dy_code { get; set; }
        public string ap_remit { get; set; }
        public decimal ap_ex_rate2 { get; set; }
        public string ap_ex_ratetype { get; set; }
        public decimal ap_base_amt { get; set; }
        public int ap_exru_seq { get; set; }
        public string ap_sub { get; set; }
        public string ap_disc_sub { get; set; }
    }
}
