//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ar_mstr_audit
    {
        public string ar_type { get; set; }
        public string ar_nbr { get; set; }
        public string ar_cust { get; set; }
        public string ar_so_nbr { get; set; }
        public string ar_xcomm_pct { get; set; }
        public Nullable<System.DateTime> ar_effdate { get; set; }
        public Nullable<System.DateTime> ar_date { get; set; }
        public string ar_cr_terms { get; set; }
        public string ar_po { get; set; }
        public Nullable<decimal> ar_amt { get; set; }
        public Nullable<decimal> ar_applied { get; set; }
        public Nullable<System.DateTime> ar_disc_date { get; set; }
        public Nullable<System.DateTime> ar_due_date { get; set; }
        public Nullable<System.DateTime> ar_expt_date { get; set; }
        public string ar_acct { get; set; }
        public string ar_cc { get; set; }
        public Nullable<decimal> ar_sales_amt { get; set; }
        public string ar_xslspsn1 { get; set; }
        public string ar_xslspsn2 { get; set; }
        public Nullable<System.DateTime> ar_paid_date { get; set; }
        public string ar_batch { get; set; }
        public string ar_disc_acct { get; set; }
        public string ar_disc_cc { get; set; }
        public string ar_ship { get; set; }
        public Nullable<bool> ar_open { get; set; }
        public Nullable<bool> ar_contested { get; set; }
        public string ar_check { get; set; }
        public Nullable<int> ar_cmtindx { get; set; }
        public string ar_user1 { get; set; }
        public string ar_user2 { get; set; }
        public string ar_curr { get; set; }
        public Nullable<decimal> ar_ex_rate { get; set; }
        public string ar_var_acct { get; set; }
        public string ar_var_cc { get; set; }
        public string ar_bank { get; set; }
        public Nullable<decimal> ar_mrgn_amt { get; set; }
        public string ar_entity { get; set; }
        public Nullable<decimal> ar_ent_ex { get; set; }
        public string ar__chr01 { get; set; }
        public string ar__chr02 { get; set; }
        public string ar__chr03 { get; set; }
        public string ar__chr04 { get; set; }
        public string ar__chr05 { get; set; }
        public Nullable<System.DateTime> ar__dte01 { get; set; }
        public Nullable<System.DateTime> ar__dte02 { get; set; }
        public Nullable<decimal> ar__dec01 { get; set; }
        public Nullable<decimal> ar__dec02 { get; set; }
        public Nullable<bool> ar__log01 { get; set; }
        public Nullable<bool> ar_draft { get; set; }
        public Nullable<System.DateTime> ar_ldue_date { get; set; }
        public Nullable<bool> ar_print { get; set; }
        public string ar_inv_cr { get; set; }
        public string ar_fr_terms { get; set; }
        public string ar_slspsn { get; set; }
        public Nullable<System.DateTime> ar_tax_date { get; set; }
        public string ar_comm_pct { get; set; }
        public string ar_bill { get; set; }
        public string ar_tax_env { get; set; }
        public string ar__qad01 { get; set; }
        public string ar__qad02 { get; set; }
        public Nullable<bool> ar__qad03 { get; set; }
        public bool ar_drft_sel { get; set; }
        public string ar_coll_mthd { get; set; }
        public decimal ar_amt_chg { get; set; }
        public decimal ar_disc_chg { get; set; }
        public decimal ar_base_amt { get; set; }
        public string ar_fsm_type { get; set; }
        public string ar_comm_amt { get; set; }
        public string ar_dy_code { get; set; }
        public int ar_dun_level { get; set; }
        public decimal ar_ex_rate2 { get; set; }
        public string ar_ex_ratetype { get; set; }
        public decimal ar_base_amt_chg { get; set; }
        public decimal ar_base_applied { get; set; }
        public string ar_base_comm_amt { get; set; }
        public int ar_exru_seq { get; set; }
        public string ar_dd_curr { get; set; }
        public decimal ar_dd_ex_rate { get; set; }
        public decimal ar_dd_ex_rate2 { get; set; }
        public int ar_dd_exru_seq { get; set; }
        public string ar_app_owner { get; set; }
        public string ar_sub { get; set; }
        public string ar_disc_sub { get; set; }
        public string ar_var_sub { get; set; }
        public bool ar_prepayment { get; set; }
        public string ar_shipfrom { get; set; }
        public string ar_customer_bank { get; set; }
        public Nullable<System.DateTime> ar_draft_disc_date { get; set; }
        public Nullable<System.DateTime> ar_recon_date { get; set; }
        public string ar_status { get; set; }
        public bool ar_customer_initiated { get; set; }
        public Nullable<System.DateTime> ar_draft_submit_date { get; set; }
        public string ar_pay_method { get; set; }
        public Nullable<System.DateTime> ar_void_date { get; set; }
        public string ar_domain { get; set; }
        public decimal oid_ar_mstr { get; set; }
    }
}
