//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ar_mstr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ar_mstr()
        {
            this.ard_det = new HashSet<ard_det>();
        }
    
        public string ar_type { get; set; }
        public string ar_nbr { get; set; }
        public string ar_cust { get; set; }
        public string ar_so_nbr { get; set; }
        public Nullable<System.DateTime> ar_effdate { get; set; }
        public Nullable<System.DateTime> ar_date { get; set; }
        public string ar_cr_terms { get; set; }
        public string ar_po { get; set; }
        public Nullable<decimal> ar_amt { get; set; }
        public Nullable<decimal> ar_applied { get; set; }
        public Nullable<System.DateTime> ar_disc_date { get; set; }
        public Nullable<System.DateTime> ar_due_date { get; set; }
        public string ar_acct { get; set; }
        public string ar_cc { get; set; }
        public Nullable<decimal> ar_sales_amt { get; set; }
        public string ar_xslspsn1 { get; set; }
        public Nullable<System.DateTime> ar_paid_date { get; set; }
        public string ar_batch { get; set; }
        public string ar_disc_acct { get; set; }
        public string ar_disc_cc { get; set; }
        public string ar_ship { get; set; }
        public Nullable<bool> ar_open { get; set; }
        public Nullable<bool> ar_contested { get; set; }
        public string ar_check { get; set; }
        public Nullable<int> ar_cmtindx { get; set; }
        public string ar_curr { get; set; }
        public Nullable<decimal> ar_ex_rate { get; set; }
        public string ar_var_acct { get; set; }
        public string ar_bank { get; set; }
        public Nullable<decimal> ar_mrgn_amt { get; set; }
        public string ar_entity { get; set; }
        public Nullable<decimal> ar_ent_ex { get; set; }
        public Nullable<bool> ar_print { get; set; }
        public Nullable<System.DateTime> ar_tax_date { get; set; }
        public string ar_bill { get; set; }
        public string ar_tax_env { get; set; }
        public Nullable<decimal> ar_base_amt { get; set; }
        public Nullable<decimal> ar_base_applied { get; set; }
        public string ar_shipfrom { get; set; }
        public string ar_domain { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ard_det> ard_det { get; set; }
    }
}
