//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class asc_mstr
    {
        public string asc_acc { get; set; }
        public string asc_sub { get; set; }
        public string asc_cc { get; set; }
        public string asc_desc { get; set; }
        public string asc_user1 { get; set; }
        public string asc_user2 { get; set; }
        public Nullable<int> asc_fpos { get; set; }
        public string asc__qadc01 { get; set; }
        public string asc_domain { get; set; }
        public decimal oid_asc_mstr { get; set; }
    }
}
