//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_mstr
    {
        public string ba_batch { get; set; }
        public string ba_userid { get; set; }
        public Nullable<System.DateTime> ba_date { get; set; }
        public Nullable<decimal> ba_ctrl { get; set; }
        public Nullable<decimal> ba_total { get; set; }
        public string ba_bank { get; set; }
        public string ba_status { get; set; }
        public string ba_user1 { get; set; }
        public string ba_user2 { get; set; }
        public string ba_module { get; set; }
        public string ba_doc_type { get; set; }
        public Nullable<decimal> ba_beg_bal { get; set; }
        public string ba__qadc01 { get; set; }
        public string ba_domain { get; set; }
        public decimal oid_ba_mstr { get; set; }
    }
}
