//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgd_det
    {
        public string bgd_acc { get; set; }
        public string bgd_cc { get; set; }
        public string bgd_project { get; set; }
        public Nullable<System.DateTime> bgd_ent_dt { get; set; }
        public int bgd_year { get; set; }
        public int bgd_per { get; set; }
        public Nullable<decimal> bgd_amt { get; set; }
        public Nullable<decimal> bgd_pct { get; set; }
        public int bgd_fpos { get; set; }
        public string bgd_entity { get; set; }
        public string bgd_code { get; set; }
        public string bgd_user1 { get; set; }
        public string bgd_user2 { get; set; }
        public string bgd_userid { get; set; }
        public Nullable<System.DateTime> bgd_date { get; set; }
        public string bgd_sub { get; set; }
        public Nullable<decimal> bgd_ecur_amt { get; set; }
        public Nullable<decimal> bgd_en_enrate { get; set; }
        public string bgd__qadc01 { get; set; }
        public string bgd_domain { get; set; }
        public decimal oid_bgd_det { get; set; }
    }
}
