//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class cm_mstr
    {
        public string cm_addr { get; set; }
        public string cm_ship { get; set; }
        public string cm_type { get; set; }
        public string cm_cr_terms { get; set; }
        public string cm_xslspsn { get; set; }
        public Nullable<int> cm__qadi01 { get; set; }
        public string cm_pr_list { get; set; }
        public Nullable<decimal> cm_disc_pct { get; set; }
        public Nullable<bool> cm_partial { get; set; }
        public Nullable<bool> cm_stmt { get; set; }
        public Nullable<bool> cm_dun { get; set; }
        public Nullable<bool> cm_fin { get; set; }
        public string cm_ar_acct { get; set; }
        public string cm_ar_cc { get; set; }
        public string cm__qadc07 { get; set; }
        public string cm__qadc01 { get; set; }
        public string cm_stmt_cyc { get; set; }
        public string cm_shipvia { get; set; }
        public string cm_rmks { get; set; }
        public string cm_resale { get; set; }
        public string cm_region { get; set; }
        public string cm__qad04 { get; set; }
        public string cm_sort { get; set; }
        public Nullable<decimal> cm_balance { get; set; }
        public Nullable<bool> cm_taxable { get; set; }
        public Nullable<System.DateTime> cm_pay_date { get; set; }
        public string cm_xslspsn2 { get; set; }
        public Nullable<int> cm__qadi02 { get; set; }
        public Nullable<int> cm_avg_pay { get; set; }
        public string cm_user1 { get; set; }
        public string cm_user2 { get; set; }
        public string cm_curr { get; set; }
        public string cm_lang { get; set; }
        public string cm_db { get; set; }
        public Nullable<bool> cm_cr_hold { get; set; }
        public string cm_cr_rating { get; set; }
        public Nullable<decimal> cm_high_cr { get; set; }
        public Nullable<System.DateTime> cm_high_date { get; set; }
        public Nullable<System.DateTime> cm_sale_date { get; set; }
        public Nullable<int> cm_invoices { get; set; }
        public Nullable<System.DateTime> cm_fin_date { get; set; }
        public Nullable<bool> cm__qad06 { get; set; }
        public string cm_fst_id { get; set; }
        public string cm_pst_id { get; set; }
        public Nullable<bool> cm_pst { get; set; }
        public Nullable<bool> cm_tax_in { get; set; }
        public string cm_site { get; set; }
        public string cm_class { get; set; }
        public string cm_taxc { get; set; }
        public string cm_bill { get; set; }
        public string cm__chr01 { get; set; }
        public string cm__chr02 { get; set; }
        public string cm__chr03 { get; set; }
        public string cm__chr04 { get; set; }
        public string cm__chr05 { get; set; }
        public string cm__chr06 { get; set; }
        public string cm__chr07 { get; set; }
        public string cm__chr08 { get; set; }
        public string cm__chr09 { get; set; }
        public string cm__chr10 { get; set; }
        public Nullable<System.DateTime> cm__dte01 { get; set; }
        public Nullable<System.DateTime> cm__dte02 { get; set; }
        public Nullable<decimal> cm__dec01 { get; set; }
        public Nullable<decimal> cm__dec02 { get; set; }
        public Nullable<bool> cm__log01 { get; set; }
        public string cm__qadc02 { get; set; }
        public string cm_fr_list { get; set; }
        public string cm_fr_terms { get; set; }
        public string cm_userid { get; set; }
        public Nullable<System.DateTime> cm_mod_date { get; set; }
        public string cm_conrep_logic { get; set; }
        public string cm_slspsn { get; set; }
        public Nullable<decimal> cm_fr_min_wt { get; set; }
        public Nullable<decimal> cm_drft_bal { get; set; }
        public Nullable<decimal> cm_lc_bal { get; set; }
        public string cm_pr_list2 { get; set; }
        public Nullable<bool> cm_fix_pr { get; set; }
        public Nullable<System.DateTime> cm_cr_update { get; set; }
        public Nullable<System.DateTime> cm_cr_review { get; set; }
        public string cm_coll_mthd { get; set; }
        public decimal cm_drft_min { get; set; }
        public decimal cm_drft_max { get; set; }
        public bool cm_drft_disc { get; set; }
        public bool cm_drft_apv { get; set; }
        public Nullable<bool> cm_internal { get; set; }
        public string cm_svc_list { get; set; }
        public Nullable<bool> cm_po_reqd { get; set; }
        public string cm_serv_terms { get; set; }
        public Nullable<decimal> cm_cr_limit { get; set; }
        public string cm_promo { get; set; }
        public bool cm_btb_cr { get; set; }
        public string cm_btb_type { get; set; }
        public int cm_ship_lt { get; set; }
        public bool cm_btb_mthd { get; set; }
        public string cm_ex_ratetype { get; set; }
        public string cm_disc_comb { get; set; }
        public string cm_scurr { get; set; }
        public string cm__qadc03 { get; set; }
        public string cm__qadc04 { get; set; }
        public string cm__qadc05 { get; set; }
        public string cm__qadc06 { get; set; }
        public Nullable<decimal> cm__qadd01 { get; set; }
        public Nullable<decimal> cm__qadd02 { get; set; }
        public Nullable<bool> cm__qadl01 { get; set; }
        public Nullable<bool> cm__qadl02 { get; set; }
        public Nullable<bool> cm__qadl03 { get; set; }
        public Nullable<bool> cm__qadl04 { get; set; }
        public Nullable<System.DateTime> cm__qadt01 { get; set; }
        public Nullable<System.DateTime> cm__qadt02 { get; set; }
        public Nullable<int> cm__qadi03 { get; set; }
        public Nullable<int> cm__qadi04 { get; set; }
        public string cm_ar_sub { get; set; }
        public string cm_sic { get; set; }
        public string cm_pay_method { get; set; }
        public bool cm_submit_prop { get; set; }
        public string cm_bank { get; set; }
        public string cm_domain { get; set; }
        public decimal oid_cm_mstr { get; set; }
    }
}
