//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class con_det
    {
        public string rpt_id { get; set; }
        public int con_id { get; set; }
        public string con_site { get; set; }
        public string con_email { get; set; }
        public string con_code { get; set; }
    }
}
