//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detailed
    {
        public int IDDataId { get; set; }
        public string OrderNumber { get; set; }
        public string Site { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string ItemNumber { get; set; }
        public string ItemDescription { get; set; }
        public string ItemGroup { get; set; }
        public Nullable<decimal> QualityAccepted { get; set; }
        public Nullable<decimal> QualityConditional { get; set; }
        public Nullable<decimal> QualityComDec { get; set; }
        public Nullable<decimal> QualityRejected { get; set; }
        public string QualityComments { get; set; }
        public Nullable<int> QualityHit { get; set; }
        public Nullable<decimal> OrderedQuantity { get; set; }
        public Nullable<decimal> ReceivedQuantity { get; set; }
        public Nullable<int> VolumeHit { get; set; }
        public Nullable<System.DateTime> ActualDeliveryTime { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryTime { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> TimeHit { get; set; }
        public Nullable<int> HitMiss { get; set; }
    }
}
