//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeManager_Backup
    {
        public int EmployeeManagerID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeNo { get; set; }
        public string DirectManager { get; set; }
        public string Source { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    }
}
