//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLocationtest
    {
        public int EmployeeLocationId { get; set; }
        public System.DateTime AlarmUpdatedTime { get; set; }
        public System.DateTime AlarmDate { get; set; }
        public string SiteId { get; set; }
        public string Username { get; set; }
        public string Action { get; set; }
        public int DevNo { get; set; }
        public string AreaDescription { get; set; }
        public string Department { get; set; }
        public string CardId { get; set; }
        public string EmpNo { get; set; }
    }
}
