//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInformation
    {
        public string Site { get; set; }
        public int EmployeeNo { get; set; }
        public string Last_Name { get; set; }
        public string Given_Names { get; set; }
        public string PayCode { get; set; }
        public string EmploymentStatus { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
