//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeException
    {
        public int ExceptionID { get; set; }
        public string EmployeeName { get; set; }
        public string ManagerName { get; set; }
        public Nullable<System.DateTime> ExceptionDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string ReasonCode { get; set; }
        public string LocationCode { get; set; }
        public string Comments { get; set; }
        public string ApprovedBy { get; set; }
        public string UserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    }
}
