//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact_SalesRC_Comments
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Text { get; set; }
        public string ObjectId { get; set; }
        public string ObjectIdDescription { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> FactSalesRcCommentsInfo_Id { get; set; }
    }
}
