//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact_SalesRC
    {
        public string Site { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string OrderNumber { get; set; }
        public string OrderLine { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceLine { get; set; }
        public string Part { get; set; }
        public Nullable<decimal> InvoiceCartonsQty { get; set; }
        public Nullable<decimal> InvoiceCartonsPriceBeforePromo { get; set; }
        public Nullable<decimal> InvoiceCartonsPromo { get; set; }
        public Nullable<decimal> InvoiceCartonsPrice { get; set; }
        public Nullable<decimal> InvoiceTotalBeforePromo { get; set; }
        public Nullable<decimal> InvoicePromo { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<decimal> OrderCartonsQty { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> ShortCartonsQty { get; set; }
        public Nullable<decimal> RejectCartonsQty { get; set; }
        public Nullable<decimal> RC_CAP { get; set; }
        public Nullable<decimal> RC_DEL { get; set; }
        public Nullable<decimal> RC_FCT { get; set; }
        public Nullable<decimal> RC_INT { get; set; }
        public Nullable<decimal> RC_NSC { get; set; }
        public Nullable<decimal> RC_PAC { get; set; }
        public Nullable<decimal> RC_PLA { get; set; }
        public Nullable<decimal> RC_QUA { get; set; }
        public Nullable<decimal> RC_RAW { get; set; }
        public Nullable<decimal> RC_SCH { get; set; }
        public Nullable<decimal> RC_WHO { get; set; }
        public Nullable<decimal> RC_1 { get; set; }
        public Nullable<decimal> RC_2 { get; set; }
        public Nullable<decimal> RC_3 { get; set; }
        public Nullable<decimal> RC_4 { get; set; }
        public Nullable<decimal> RC_5 { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdateBy { get; set; }
        public string Id { get; set; }
        public string Status { get; set; }
        public string PurchaseOrder { get; set; }
        public Nullable<decimal> InvoiceUnitsQty { get; set; }
        public Nullable<decimal> InvoiceKgsQty { get; set; }
        public Nullable<decimal> OrderUnitsQty { get; set; }
        public Nullable<decimal> OrderKgsQty { get; set; }
    }
}
