//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class glc_cal
    {
        public Nullable<int> glc_year { get; set; }
        public Nullable<int> glc_per { get; set; }
        public Nullable<System.DateTime> glc_start { get; set; }
        public Nullable<System.DateTime> glc_end { get; set; }
        public Nullable<bool> glc__qad01 { get; set; }
        public Nullable<bool> glc__qad04 { get; set; }
        public Nullable<bool> glc__qad03 { get; set; }
        public string glc__qad02 { get; set; }
        public string glc_user1 { get; set; }
        public string glc_user2 { get; set; }
        public bool glc_yr_end { get; set; }
        public string glc_domain { get; set; }
        public decimal oid_glc_cal { get; set; }
    }
}
