//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class gltr_hist_audit
    {
        public string gltr_acc { get; set; }
        public string gltr_ctr { get; set; }
        public string gltr_tr_type { get; set; }
        public Nullable<System.DateTime> gltr_ent_dt { get; set; }
        public Nullable<System.DateTime> gltr_eff_dt { get; set; }
        public Nullable<decimal> gltr_amt { get; set; }
        public string gltr_ref { get; set; }
        public string gltr_desc { get; set; }
        public Nullable<bool> gltr_unb { get; set; }
        public string gltr_user { get; set; }
        public string gltr_project { get; set; }
        public string gltr_error { get; set; }
        public string gltr_batch { get; set; }
        public string gltr_curr { get; set; }
        public Nullable<decimal> gltr_curramt { get; set; }
        public string gltr_entity { get; set; }
        public Nullable<int> gltr_line { get; set; }
        public Nullable<decimal> gltr_ex_rate { get; set; }
        public Nullable<bool> gltr_export { get; set; }
        public string gltr_addr { get; set; }
        public string gltr_doc { get; set; }
        public string gltr_doc_typ { get; set; }
        public string gltr_user1 { get; set; }
        public string gltr_user2 { get; set; }
        public string gltr_fx_ind { get; set; }
        public string gltr_sub { get; set; }
        public Nullable<bool> gltr_rflag { get; set; }
        public Nullable<decimal> gltr_ecur_amt { get; set; }
        public Nullable<decimal> gltr_en_exrate { get; set; }
        public string gltr__qadc01 { get; set; }
        public bool gltr_correction { get; set; }
        public string gltr_dy_code { get; set; }
        public string gltr_dy_num { get; set; }
        public decimal gltr_ex_rate2 { get; set; }
        public string gltr_ex_ratetype { get; set; }
        public decimal gltr_en_exrate2 { get; set; }
        public int gltr_exru_seq { get; set; }
        public int gltr_en_exru_seq { get; set; }
        public string gltr_src_desc { get; set; }
        public string gltr_domain { get; set; }
        public decimal oid_gltr_hist { get; set; }
    }
}
