//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class idh_hist
    {
        public string idh_nbr { get; set; }
        public Nullable<System.DateTime> idh_due_date { get; set; }
        public Nullable<int> idh_line { get; set; }
        public string idh_part { get; set; }
        public Nullable<decimal> idh_qty_ord { get; set; }
        public Nullable<decimal> idh_qty_inv { get; set; }
        public Nullable<decimal> idh_price { get; set; }
        public Nullable<decimal> idh_std_cost { get; set; }
        public string idh_acct { get; set; }
        public string idh_cc { get; set; }
        public string idh_inv_nbr { get; set; }
        public string idh_site { get; set; }
        public string idh_prodline { get; set; }
        public string idh_sub { get; set; }
        public string idh_custref { get; set; }
        public string idh_type { get; set; }
        public string idh_status { get; set; }
        public Nullable<decimal> idh_list_pr { get; set; }
    }
}
