//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ih_hist_audit
    {
        public string ih_nbr { get; set; }
        public string ih_cust { get; set; }
        public string ih_ship { get; set; }
        public Nullable<System.DateTime> ih_ord_date { get; set; }
        public Nullable<System.DateTime> ih_req_date { get; set; }
        public Nullable<System.DateTime> ih_due_date { get; set; }
        public string ih_rmks { get; set; }
        public string ih_cr_terms { get; set; }
        public string ih_fob { get; set; }
        public string ih_po { get; set; }
        public string ih_shipvia { get; set; }
        public Nullable<bool> ih_partial { get; set; }
        public Nullable<bool> ih_print_so { get; set; }
        public string ih_inv_nbr { get; set; }
        public string ih_pr_list { get; set; }
        public string ih_xslspsn { get; set; }
        public string ih_source { get; set; }
        public string ih_xcomm_pct { get; set; }
        public string ih_cr_card { get; set; }
        public Nullable<bool> ih_print_pl { get; set; }
        public string ih_cr_init { get; set; }
        public string ih_stat { get; set; }
        public Nullable<decimal> ih__qad01 { get; set; }
        public Nullable<decimal> ih__qad02 { get; set; }
        public Nullable<decimal> ih__qad03 { get; set; }
        public Nullable<decimal> ih_disc_pct { get; set; }
        public string ih_tax_pct { get; set; }
        public Nullable<decimal> ih_prepaid { get; set; }
        public Nullable<bool> ih_to_inv { get; set; }
        public Nullable<bool> ih_invoiced { get; set; }
        public string ih_ar_acct { get; set; }
        public string ih_ar_cc { get; set; }
        public Nullable<System.DateTime> ih_inv_date { get; set; }
        public Nullable<System.DateTime> ih_ship_date { get; set; }
        public Nullable<bool> ih_taxable { get; set; }
        public Nullable<int> ih_cmtindx { get; set; }
        public Nullable<int> ih__qad04 { get; set; }
        public string ih_user1 { get; set; }
        public string ih_user2 { get; set; }
        public string ih_curr { get; set; }
        public Nullable<decimal> ih_ex_rate { get; set; }
        public string ih_lang { get; set; }
        public string ih_type { get; set; }
        public Nullable<System.DateTime> ih_conf_date { get; set; }
        public Nullable<int> ih_rev { get; set; }
        public string ih_bol { get; set; }
        public string ih__qad05 { get; set; }
        public Nullable<bool> ih_pst { get; set; }
        public string ih_fst_id { get; set; }
        public Nullable<decimal> ih_trl1_amt { get; set; }
        public string ih_trl1_cd { get; set; }
        public Nullable<decimal> ih_trl2_amt { get; set; }
        public string ih_trl2_cd { get; set; }
        public Nullable<decimal> ih_trl3_amt { get; set; }
        public string ih_trl3_cd { get; set; }
        public Nullable<decimal> ih_weight { get; set; }
        public string ih_weight_um { get; set; }
        public Nullable<decimal> ih_size { get; set; }
        public string ih_size_um { get; set; }
        public Nullable<int> ih_cartons { get; set; }
        public string ih_site { get; set; }
        public string ih_quote { get; set; }
        public string ih_taxc { get; set; }
        public string ih__chr01 { get; set; }
        public string ih__chr02 { get; set; }
        public string ih__chr03 { get; set; }
        public string ih__chr04 { get; set; }
        public string ih__chr05 { get; set; }
        public string ih__chr06 { get; set; }
        public string ih__chr07 { get; set; }
        public string ih__chr08 { get; set; }
        public string ih__chr09 { get; set; }
        public string ih__chr10 { get; set; }
        public Nullable<System.DateTime> ih__dte01 { get; set; }
        public Nullable<System.DateTime> ih__dte02 { get; set; }
        public Nullable<decimal> ih__dec01 { get; set; }
        public Nullable<decimal> ih__dec02 { get; set; }
        public Nullable<bool> ih__log01 { get; set; }
        public Nullable<bool> ih_credit { get; set; }
        public string ih_inv_cr { get; set; }
        public string ih_project { get; set; }
        public Nullable<decimal> ih_pst_pct { get; set; }
        public string ih_fr_list { get; set; }
        public string ih_fr_terms { get; set; }
        public string ih_comm_pct { get; set; }
        public string ih_slspsn { get; set; }
        public Nullable<bool> ih_fix_rate { get; set; }
        public Nullable<decimal> ih_ent_ex { get; set; }
        public string ih_bill { get; set; }
        public Nullable<bool> ih_print_bl { get; set; }
        public string ih_userid { get; set; }
        public Nullable<System.DateTime> ih_tax_date { get; set; }
        public string ih_channel { get; set; }
        public string ih_inv_mthd { get; set; }
        public string ih_pst_id { get; set; }
        public string ih_fsm_type { get; set; }
        public string ih_bank { get; set; }
        public Nullable<decimal> ih_fr_min_wt { get; set; }
        public string ih_pr_list2 { get; set; }
        public string ih_tax_env { get; set; }
        public string ih_tax_usage { get; set; }
        public string ih_sa_nbr { get; set; }
        public string ih_crprlist { get; set; }
        public Nullable<bool> ih_ship_eng { get; set; }
        public Nullable<System.DateTime> ih_cncl_date { get; set; }
        public string ih_conrep { get; set; }
        public Nullable<bool> ih_sched { get; set; }
        public Nullable<bool> ih_fix_pr { get; set; }
        public string ih_sch_mthd { get; set; }
        public string ih_ca_nbr { get; set; }
        public string ih_fcg_code { get; set; }
        public Nullable<System.DateTime> ih_mod_date { get; set; }
        public Nullable<System.DateTime> ih_priced_dt { get; set; }
        public Nullable<System.DateTime> ih_pricing_dt { get; set; }
        public Nullable<decimal> ih_rstk_pct { get; set; }
        public string ih__qadc01 { get; set; }
        public string ih__qadc02 { get; set; }
        public string ih__qadc03 { get; set; }
        public string ih__qadc04 { get; set; }
        public string ih__qadc05 { get; set; }
        public Nullable<System.DateTime> ih__qadt01 { get; set; }
        public Nullable<System.DateTime> ih__qadt02 { get; set; }
        public Nullable<System.DateTime> ih__qadt03 { get; set; }
        public Nullable<decimal> ih__qadd01 { get; set; }
        public Nullable<decimal> ih__qadd02 { get; set; }
        public Nullable<decimal> ih__qadd03 { get; set; }
        public Nullable<int> ih__qadi01 { get; set; }
        public Nullable<int> ih__qadi02 { get; set; }
        public Nullable<int> ih__qadi03 { get; set; }
        public Nullable<bool> ih__qadl01 { get; set; }
        public Nullable<bool> ih__qadl02 { get; set; }
        public Nullable<bool> ih__qadl03 { get; set; }
        public bool ih_primary { get; set; }
        public string ih_cust_po { get; set; }
        public Nullable<bool> ih_secondary { get; set; }
        public string ih_ship_po { get; set; }
        public decimal ih_ex_rate2 { get; set; }
        public string ih_ex_ratetype { get; set; }
        public string ih_div { get; set; }
        public int ih_exru_seq { get; set; }
        public Nullable<int> ih_export_batch { get; set; }
        public Nullable<System.DateTime> ih_export_date { get; set; }
        public Nullable<int> ih_export_time { get; set; }
        public string ih_ar_sub { get; set; }
        public decimal ih_prep_tax { get; set; }
        public bool ih_custref_val { get; set; }
        public string ih_domain { get; set; }
        public decimal oid_ih_hist { get; set; }
    }
}
