//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_mstr
    {
        public string in_part { get; set; }
        public string in_site { get; set; }
        public Nullable<decimal> in_qty_oh { get; set; }
        public Nullable<decimal> in_qty_req { get; set; }
        public Nullable<decimal> in_qty_all { get; set; }
        public Nullable<decimal> in_qty_ord { get; set; }
        public Nullable<decimal> in_qty_chg { get; set; }
        public Nullable<decimal> in_qty_avail { get; set; }
        public Nullable<decimal> in_sls_chg { get; set; }
        public Nullable<decimal> in_iss_chg { get; set; }
        public Nullable<System.DateTime> in_iss_date { get; set; }
        public Nullable<System.DateTime> in_rec_date { get; set; }
        public Nullable<System.DateTime> in_cnt_date { get; set; }
        public Nullable<decimal> in_avg_iss { get; set; }
        public Nullable<decimal> in_avg_sls { get; set; }
        public Nullable<System.DateTime> in_avg_date { get; set; }
        public string in_user1 { get; set; }
        public string in_user2 { get; set; }
        public Nullable<decimal> in_rop { get; set; }
        public Nullable<decimal> in_sfty_stk { get; set; }
        public Nullable<decimal> in_qty_nonet { get; set; }
        public Nullable<bool> in_mrp { get; set; }
        public string in_gl_set { get; set; }
        public string in_cur_set { get; set; }
        public string in_abc { get; set; }
        public Nullable<int> in_avg_int { get; set; }
        public Nullable<int> in_cyc_int { get; set; }
        public int in_level { get; set; }
        public Nullable<decimal> in_assay { get; set; }
        public string in_grade { get; set; }
        public string in_loc { get; set; }
        public string in_loc_type { get; set; }
        public Nullable<int> in_proj_use { get; set; }
        public Nullable<bool> in_rollup { get; set; }
        public string in_rollup_id { get; set; }
        public string in_rctpo_status { get; set; }
        public string in_rctwo_status { get; set; }
        public Nullable<bool> in_rctpo_active { get; set; }
        public Nullable<bool> in_rctwo_active { get; set; }
        public string in__qadc01 { get; set; }
        public bool in_wh { get; set; }
        public string in_gl_cost_site { get; set; }
        public decimal in_cust_consign_qty { get; set; }
        public decimal in_supp_consign_qty { get; set; }
        public string in_domain { get; set; }
        public decimal oid_in_mstr { get; set; }
    }
}
