//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ld_det
    {
        public string ld_loc { get; set; }
        public string ld_part { get; set; }
        public Nullable<System.DateTime> ld_date { get; set; }
        public decimal ld_qty_oh { get; set; }
        public string ld_lot { get; set; }
        public string ld_ref { get; set; }
        public Nullable<System.DateTime> ld_cnt_date { get; set; }
        public Nullable<decimal> ld_assay { get; set; }
        public Nullable<System.DateTime> ld_expire { get; set; }
        public string ld_user1 { get; set; }
        public string ld_user2 { get; set; }
        public string ld_site { get; set; }
        public string ld_status { get; set; }
        public Nullable<decimal> ld_qty_all { get; set; }
        public string ld_grade { get; set; }
        public Nullable<decimal> ld_qty_frz { get; set; }
        public Nullable<System.DateTime> ld_date_frz { get; set; }
        public string ld_vd_lot { get; set; }
        public Nullable<int> ld_cmtindx { get; set; }
        public Nullable<decimal> ld_work { get; set; }
        public string ld__chr01 { get; set; }
        public string ld__chr02 { get; set; }
        public string ld__chr03 { get; set; }
        public string ld__chr04 { get; set; }
        public string ld__chr05 { get; set; }
        public Nullable<System.DateTime> ld__dte01 { get; set; }
        public Nullable<System.DateTime> ld__dte02 { get; set; }
        public Nullable<decimal> ld__dec01 { get; set; }
        public Nullable<decimal> ld__dec02 { get; set; }
        public Nullable<bool> ld__log01 { get; set; }
        public Nullable<decimal> ld_cost { get; set; }
        public string ld_rev { get; set; }
        public decimal ld_cust_consign_qty { get; set; }
        public decimal ld_supp_consign_qty { get; set; }
        public string ld_domain { get; set; }
        public decimal oid_ld_det { get; set; }
    }
}
