//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MacroOutputBDL
    {
        public Nullable<System.DateTime> WeekEnding { get; set; }
        public string EmpNo { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int RecID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public string PayCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Start { get; set; }
        public Nullable<decimal> Finish { get; set; }
        public Nullable<decimal> MealBreak { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<decimal> CodeHours { get; set; }
        public Nullable<decimal> OTHours { get; set; }
        public Nullable<decimal> AF15 { get; set; }
        public Nullable<decimal> EM20 { get; set; }
        public Nullable<decimal> NS30 { get; set; }
        public Nullable<decimal> SAX15 { get; set; }
        public Nullable<decimal> SAOTX2 { get; set; }
        public Nullable<decimal> SUX15 { get; set; }
        public Nullable<decimal> SUX2 { get; set; }
        public Nullable<decimal> DOTX15 { get; set; }
        public Nullable<decimal> DOTX2 { get; set; }
        public Nullable<decimal> WOTX2 { get; set; }
        public Nullable<decimal> OT25 { get; set; }
        public Nullable<int> MEA3 { get; set; }
        public Nullable<decimal> CALLX15 { get; set; }
        public Nullable<decimal> CALLX2 { get; set; }
        public Nullable<decimal> ORDHours { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
