//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrp_det
    {
        public string mrp_dataset { get; set; }
        public string mrp_part { get; set; }
        public string mrp_nbr { get; set; }
        public string mrp_line { get; set; }
        public Nullable<System.DateTime> mrp_rel_date { get; set; }
        public Nullable<System.DateTime> mrp_due_date { get; set; }
        public Nullable<decimal> mrp_qty { get; set; }
        public string mrp_type { get; set; }
        public string mrp_detail { get; set; }
        public Nullable<bool> mrp__qad01 { get; set; }
        public string mrp_site { get; set; }
        public string mrp_user1 { get; set; }
        public string mrp_user2 { get; set; }
        public string mrp_line2 { get; set; }
        public string mrp_ord_site { get; set; }
        public int mrp_keyid { get; set; }
        public string mrp_domain { get; set; }
        public decimal oid_mrp_det { get; set; }
    }
}
