//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OldPurchaseOrderContext : DbContext
    {
        public OldPurchaseOrderContext()
            : base("name=OldPurchaseOrderContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblAmendment> tblAmendments { get; set; }
        public virtual DbSet<tblAPSubstitutionLog> tblAPSubstitutionLogs { get; set; }
        public virtual DbSet<tblBudgetDetail> tblBudgetDetails { get; set; }
        public virtual DbSet<tblBudgetHeader> tblBudgetHeaders { get; set; }
        public virtual DbSet<tblCapex> tblCapexes { get; set; }
        public virtual DbSet<tblCapexApprover> tblCapexApprovers { get; set; }
        public virtual DbSet<tblCapexAuthoriser> tblCapexAuthorisers { get; set; }
        public virtual DbSet<tblCapexAuthoriserList> tblCapexAuthoriserLists { get; set; }
        public virtual DbSet<tblCapexLimit> tblCapexLimits { get; set; }
        public virtual DbSet<tblCapexRole> tblCapexRoles { get; set; }
        public virtual DbSet<tblCapexRoleLimit> tblCapexRoleLimits { get; set; }
        public virtual DbSet<tblCapexRouting> tblCapexRoutings { get; set; }
        public virtual DbSet<tblControl> tblControls { get; set; }
        public virtual DbSet<tblCostCentre> tblCostCentres { get; set; }
        public virtual DbSet<tblCreditCardPurchas> tblCreditCardPurchases { get; set; }
        public virtual DbSet<tblCurrencyRate> tblCurrencyRates { get; set; }
        public virtual DbSet<tblEntity> tblEntities { get; set; }
        public virtual DbSet<tblEntityCCAcc> tblEntityCCAccs { get; set; }
        public virtual DbSet<tblGroup> tblGroups { get; set; }
        public virtual DbSet<tblGroupMember> tblGroupMembers { get; set; }
        public virtual DbSet<tblPerformanceLog> tblPerformanceLogs { get; set; }
        public virtual DbSet<tblPODelivery> tblPODeliveries { get; set; }
        public virtual DbSet<tblPODetail> tblPODetails { get; set; }
        public virtual DbSet<tblPODetailReceipt> tblPODetailReceipts { get; set; }
        public virtual DbSet<tblPOHeader> tblPOHeaders { get; set; }
        public virtual DbSet<tblPOPhasing> tblPOPhasings { get; set; }
        public virtual DbSet<tblRoutingAccountLimit> tblRoutingAccountLimits { get; set; }
        public virtual DbSet<tblRoutingList> tblRoutingLists { get; set; }
        public virtual DbSet<tblRoutingSubstitute> tblRoutingSubstitutes { get; set; }
        public virtual DbSet<tblRoutingTable> tblRoutingTables { get; set; }
        public virtual DbSet<tblSite> tblSites { get; set; }
        public virtual DbSet<tblStagingAccCC> tblStagingAccCCs { get; set; }
        public virtual DbSet<tblStagingAccount> tblStagingAccounts { get; set; }
        public virtual DbSet<tblStagingAccountsTMP> tblStagingAccountsTMPs { get; set; }
        public virtual DbSet<tblStagingCostCentre> tblStagingCostCentres { get; set; }
        public virtual DbSet<tblStagingCostCentresDEV> tblStagingCostCentresDEVs { get; set; }
        public virtual DbSet<tblStagingEmployee> tblStagingEmployees { get; set; }
        public virtual DbSet<tblStagingEmployeesDEV> tblStagingEmployeesDEVs { get; set; }
        public virtual DbSet<tblStagingLevel> tblStagingLevels { get; set; }
        public virtual DbSet<tblSubAccount> tblSubAccounts { get; set; }
        public virtual DbSet<tblSubscription> tblSubscriptions { get; set; }
        public virtual DbSet<tblSupplierNew> tblSupplierNews { get; set; }
        public virtual DbSet<tblTransaction> tblTransactions { get; set; }
        public virtual DbSet<tblUserDefault> tblUserDefaults { get; set; }
        public virtual DbSet<tblSupplier> tblSuppliers { get; set; }
        public virtual DbSet<tblSupplierTemp1> tblSupplierTemp1 { get; set; }
        public virtual DbSet<vwEntityCCAcc> vwEntityCCAccs { get; set; }
        public virtual DbSet<vwAp_det_oldpo> vwAp_det_oldpo { get; set; }
        public virtual DbSet<vwAp_grni_rf_oldpo> vwAp_grni_rf_oldpo { get; set; }
        public virtual DbSet<vwAp_mstr_oldpo> vwAp_mstr_oldpo { get; set; }
    }
}
