//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OldTNAContext : DbContext
    {
        public OldTNAContext()
            : base("name=OldTNAContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveDirectoryTerminatedExclude> ActiveDirectoryTerminatedExclude { get; set; }
        public virtual DbSet<ApprovalList> ApprovalList { get; set; }
        public virtual DbSet<con_det> con_det { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<EmployeeException> EmployeeException { get; set; }
        public virtual DbSet<EmployeeInformation> EmployeeInformation { get; set; }
        public virtual DbSet<EmployeeLocation> EmployeeLocation { get; set; }
        public virtual DbSet<EmployeeLocationNew> EmployeeLocationNew { get; set; }
        public virtual DbSet<EmployeeLocationNew1> EmployeeLocationNew1 { get; set; }
        public virtual DbSet<EmployeeLocationtest> EmployeeLocationtest { get; set; }
        public virtual DbSet<EmployeeManager> EmployeeManager { get; set; }
        public virtual DbSet<EmployeeTotalTime> EmployeeTotalTime { get; set; }
        public virtual DbSet<GLCodeMapping> GLCodeMapping { get; set; }
        public virtual DbSet<LabourHireCompany> LabourHireCompany { get; set; }
        public virtual DbSet<LabourHireCompanyRate> LabourHireCompanyRate { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<MacroOutputBDL> MacroOutputBDL { get; set; }
        public virtual DbSet<MacroOutputBNE> MacroOutputBNE { get; set; }
        public virtual DbSet<MacroOutputPTH> MacroOutputPTH { get; set; }
        public virtual DbSet<MacroOutputSYD> MacroOutputSYD { get; set; }
        public virtual DbSet<Reason> Reason { get; set; }
        public virtual DbSet<rpt_det> rpt_det { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<STPControl> STPControl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblActiveDays> tblActiveDays { get; set; }
        public virtual DbSet<tblTransaction> tblTransaction { get; set; }
        public virtual DbSet<tic_ctrl> tic_ctrl { get; set; }
        public virtual DbSet<tic_det> tic_det { get; set; }
        public virtual DbSet<tid_allowances> tid_allowances { get; set; }
        public virtual DbSet<tid_det> tid_det { get; set; }
        public virtual DbSet<tid_det_archive> tid_det_archive { get; set; }
        public virtual DbSet<tit_alarm_archive> tit_alarm_archive { get; set; }
        public virtual DbSet<tit_departments> tit_departments { get; set; }
        public virtual DbSet<tit_users> tit_users { get; set; }
        public virtual DbSet<tit_users_new> tit_users_new { get; set; }
        public virtual DbSet<tit_users_static_old> tit_users_static_old { get; set; }
        public virtual DbSet<tra_det> tra_det { get; set; }
        public virtual DbSet<UploadQueue> UploadQueue { get; set; }
        public virtual DbSet<UserAlias> UserAlias { get; set; }
        public virtual DbSet<EmployeeExclude> EmployeeExclude { get; set; }
        public virtual DbSet<EmployeeManager_Backup> EmployeeManager_Backup { get; set; }
        public virtual DbSet<km01> km01 { get; set; }
        public virtual DbSet<MacroOutputBDL_EBABackDate> MacroOutputBDL_EBABackDate { get; set; }
        public virtual DbSet<RosterOnPaycodeMapping> RosterOnPaycodeMapping { get; set; }
        public virtual DbSet<SMSEmployee> SMSEmployee { get; set; }
        public virtual DbSet<ticket25457> ticket25457 { get; set; }
        public virtual DbSet<tid_ctrl> tid_ctrl { get; set; }
        public virtual DbSet<tid_det_EBABackDate> tid_det_EBABackDate { get; set; }
        public virtual DbSet<tid_det_roster_on> tid_det_roster_on { get; set; }
        public virtual DbSet<tid_tl_det> tid_tl_det { get; set; }
        public virtual DbSet<tit_alarm> tit_alarm { get; set; }
        public virtual DbSet<tit_alarm_from_tid_det> tit_alarm_from_tid_det { get; set; }
        public virtual DbSet<tit_alarm_from_tid_det_detailed> tit_alarm_from_tid_det_detailed { get; set; }
        public virtual DbSet<tit_alarm_test> tit_alarm_test { get; set; }
        public virtual DbSet<tit_dev> tit_dev { get; set; }
        public virtual DbSet<Tmp_tit_alarm> Tmp_tit_alarm { get; set; }
        public virtual DbSet<tna_ctrl> tna_ctrl { get; set; }
        public virtual DbSet<WeekendWorkers> WeekendWorkers { get; set; }
    }
}
