//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_mstr
    {
        public string pl_prod_line { get; set; }
        public string pl_desc { get; set; }
        public string pl_sls_acct { get; set; }
        public string pl_inv_acct { get; set; }
        public string pl_wip_acct { get; set; }
        public string pl_cog_acct { get; set; }
        public string pl_pur_acct { get; set; }
        public string pl_scrp_acct { get; set; }
        public string pl_dscr_acct { get; set; }
        public string pl_sls_cc { get; set; }
        public string pl_inv_cc { get; set; }
        public string pl_wip_cc { get; set; }
        public string pl_cog_cc { get; set; }
        public string pl_pur_cc { get; set; }
        public string pl_scrp_cc { get; set; }
        public string pl_dscr_cc { get; set; }
        public string pl_ppv_acct { get; set; }
        public string pl_ppv_cc { get; set; }
        public string pl_rcpt_acct { get; set; }
        public string pl_rcpt_cc { get; set; }
        public string pl_dsc_acct { get; set; }
        public string pl_dsc_cc { get; set; }
        public string pl_wvar_acct { get; set; }
        public string pl_wvar_cc { get; set; }
        public string pl_taxc { get; set; }
        public Nullable<bool> pl_taxable { get; set; }
        public string pl_user1 { get; set; }
        public string pl_user2 { get; set; }
        public Nullable<bool> pl_pst { get; set; }
        public string pl_esls_acct { get; set; }
        public string pl_esls_cc { get; set; }
        public string pl__chr01 { get; set; }
        public string pl__chr02 { get; set; }
        public string pl__chr03 { get; set; }
        public string pl__chr04 { get; set; }
        public string pl__chr05 { get; set; }
        public Nullable<System.DateTime> pl__dte01 { get; set; }
        public Nullable<System.DateTime> pl__dte02 { get; set; }
        public Nullable<decimal> pl__dec01 { get; set; }
        public Nullable<decimal> pl__dec02 { get; set; }
        public Nullable<bool> pl__log01 { get; set; }
        public string pl_group { get; set; }
        public string pl_division { get; set; }
        public string pl_cchg_acct { get; set; }
        public string pl_cchg_cc { get; set; }
        public string pl_userid { get; set; }
        public Nullable<System.DateTime> pl_mod_date { get; set; }
        public string pl_cmtl_acct { get; set; }
        public string pl_cmtl_cc { get; set; }
        public string pl_clbr_acct { get; set; }
        public string pl_clbr_cc { get; set; }
        public string pl_cbdn_acct { get; set; }
        public string pl_cbdn_cc { get; set; }
        public string pl_covh_acct { get; set; }
        public string pl_covh_cc { get; set; }
        public string pl_csub_acct { get; set; }
        public string pl_csub_cc { get; set; }
        public string pl_apvr_acct { get; set; }
        public string pl_apvr_cc { get; set; }
        public string pl_apvu_acct { get; set; }
        public string pl_apvu_cc { get; set; }
        public string pl_ovh_acct { get; set; }
        public string pl_ovh_cc { get; set; }
        public string pl_mvar_acct { get; set; }
        public string pl_mvar_cc { get; set; }
        public string pl_mvrr_acct { get; set; }
        public string pl_mvrr_cc { get; set; }
        public string pl_svar_acct { get; set; }
        public string pl_svar_cc { get; set; }
        public string pl_svrr_acct { get; set; }
        public string pl_svrr_cc { get; set; }
        public string pl_cop_acct { get; set; }
        public string pl_cop_cc { get; set; }
        public string pl_flr_acct { get; set; }
        public string pl_flr_cc { get; set; }
        public string pl__qadc06 { get; set; }
        public string pl__qadc07 { get; set; }
        public string pl__qadc08 { get; set; }
        public string pl__qadc09 { get; set; }
        public string pl_rmar_acct { get; set; }
        public string pl_rmar_cc { get; set; }
        public string pl__qadc12 { get; set; }
        public string pl__qadc13 { get; set; }
        public string pl__qadc14 { get; set; }
        public string pl__qadc15 { get; set; }
        public string pl_fiscal_class { get; set; }
        public string pl_xvar_acct { get; set; }
        public string pl_xvar_cc { get; set; }
        public string pl_fslbr_acct { get; set; }
        public string pl_fsbdn_acct { get; set; }
        public string pl__qadc10 { get; set; }
        public string pl_fsexp_acct { get; set; }
        public string pl_fsexd_acct { get; set; }
        public string pl_fslbr_cc { get; set; }
        public string pl_fsbdn_cc { get; set; }
        public string pl__qadc11 { get; set; }
        public string pl_fsexp_cc { get; set; }
        public string pl_fsexd_cc { get; set; }
        public string pl_fsrc_inv_acct { get; set; }
        public string pl_fsrc_inv_cc { get; set; }
        public string pl_fscm_inv_acct { get; set; }
        public string pl_fscm_inv_cc { get; set; }
        public string pl__qadc01 { get; set; }
        public string pl__qadc02 { get; set; }
        public string pl__qadc03 { get; set; }
        public string pl__qadc04 { get; set; }
        public string pl__qadc05 { get; set; }
        public Nullable<decimal> pl__qadd01 { get; set; }
        public string pl_apvr_sub { get; set; }
        public string pl_apvu_sub { get; set; }
        public string pl_cbdn_sub { get; set; }
        public string pl_cchg_sub { get; set; }
        public string pl_clbr_sub { get; set; }
        public string pl_cmtl_sub { get; set; }
        public string pl_cog_sub { get; set; }
        public string pl_cop_sub { get; set; }
        public string pl_covh_sub { get; set; }
        public string pl_csub_sub { get; set; }
        public string pl_dscr_sub { get; set; }
        public string pl_dsc_sub { get; set; }
        public string pl_flr_sub { get; set; }
        public string pl_fsbdn_sub { get; set; }
        public string pl_fscm_inv_sub { get; set; }
        public string pl_fsexd_sub { get; set; }
        public string pl_fsexp_sub { get; set; }
        public string pl_fslbr_sub { get; set; }
        public string pl_fsrc_inv_sub { get; set; }
        public string pl_inv_sub { get; set; }
        public string pl_mvar_sub { get; set; }
        public string pl_mvrr_sub { get; set; }
        public string pl_ovh_sub { get; set; }
        public string pl_ppv_sub { get; set; }
        public string pl_pur_sub { get; set; }
        public string pl_rcpt_sub { get; set; }
        public string pl_rmar_sub { get; set; }
        public string pl_scrp_sub { get; set; }
        public string pl_sls_sub { get; set; }
        public string pl_svar_sub { get; set; }
        public string pl_svrr_sub { get; set; }
        public string pl_wip_sub { get; set; }
        public string pl_wvar_sub { get; set; }
        public string pl_xvar_sub { get; set; }
        public string pl_xfer_acct { get; set; }
        public string pl_xfer_sub { get; set; }
        public string pl_xfer_cc { get; set; }
        public string pl_fsdef_acct { get; set; }
        public string pl_fsdef_sub { get; set; }
        public string pl_fsdef_cc { get; set; }
        public string pl_fsaccr_acct { get; set; }
        public string pl_fsaccr_sub { get; set; }
        public string pl_fsaccr_cc { get; set; }
        public string pl_domain { get; set; }
    }
}
