//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class po_mstr
    {
        public string po_nbr { get; set; }
        public string po_vend { get; set; }
        public string po_ship { get; set; }
        public Nullable<System.DateTime> po_ord_date { get; set; }
        public string po_rmks { get; set; }
        public string po_cr_terms { get; set; }
        public string po_buyer { get; set; }
        public string po_shipvia { get; set; }
        public string po_fob { get; set; }
        public string po_bill { get; set; }
        public Nullable<bool> po__qad04 { get; set; }
        public Nullable<bool> po_partial { get; set; }
        public Nullable<decimal> po_rev { get; set; }
        public string po_stat { get; set; }
        public string po_ap_acct { get; set; }
        public string po_ap_cc { get; set; }
        public Nullable<decimal> po_frt { get; set; }
        public Nullable<decimal> po_serv_chg { get; set; }
        public Nullable<decimal> po_spec_chg { get; set; }
        public string po_tax_pct { get; set; }
        public Nullable<decimal> po_disc_pct { get; set; }
        public Nullable<decimal> po_prepaid { get; set; }
        public string po_contact { get; set; }
        public Nullable<bool> po_confirm { get; set; }
        public Nullable<int> po_cmtindx { get; set; }
        public Nullable<bool> po_print { get; set; }
        public Nullable<System.DateTime> po_cls_date { get; set; }
        public Nullable<bool> po_taxable { get; set; }
        public string po_user1 { get; set; }
        public string po_user2 { get; set; }
        public string po_curr { get; set; }
        public Nullable<decimal> po_ex_rate { get; set; }
        public string po_lang { get; set; }
        public string po_fst_id { get; set; }
        public string po_pst_id { get; set; }
        public Nullable<bool> po_pst { get; set; }
        public string po_duty_type { get; set; }
        public Nullable<decimal> po__qad05 { get; set; }
        public string po__qad07 { get; set; }
        public string po__qad08 { get; set; }
        public string po_site { get; set; }
        public string po_blanket { get; set; }
        public Nullable<System.DateTime> po__qad01 { get; set; }
        public Nullable<int> po__qad02 { get; set; }
        public string po__qad03 { get; set; }
        public string po_contract { get; set; }
        public string po_del_to { get; set; }
        public Nullable<System.DateTime> po_due_date { get; set; }
        public Nullable<System.DateTime> po_eff_strt { get; set; }
        public Nullable<System.DateTime> po_eff_to { get; set; }
        public Nullable<decimal> po_est_value { get; set; }
        public Nullable<bool> po__qad06 { get; set; }
        public string po_project { get; set; }
        public Nullable<int> po_rel_nbr { get; set; }
        public string po_req_id { get; set; }
        public string po_type { get; set; }
        public string po_user_id { get; set; }
        public Nullable<decimal> po__qad09 { get; set; }
        public Nullable<bool> po_release { get; set; }
        public Nullable<bool> po_recurr { get; set; }
        public string po_cycl { get; set; }
        public string po__chr01 { get; set; }
        public string po__chr02 { get; set; }
        public string po__chr03 { get; set; }
        public string po__chr04 { get; set; }
        public string po__chr05 { get; set; }
        public string po__chr06 { get; set; }
        public string po__chr07 { get; set; }
        public string po__chr08 { get; set; }
        public string po__chr09 { get; set; }
        public string po__chr10 { get; set; }
        public Nullable<System.DateTime> po__dte01 { get; set; }
        public Nullable<System.DateTime> po__dte02 { get; set; }
        public Nullable<decimal> po__dec01 { get; set; }
        public Nullable<decimal> po__dec02 { get; set; }
        public Nullable<bool> po__log01 { get; set; }
        public string po_inv_mthd { get; set; }
        public Nullable<bool> po_fix_rate { get; set; }
        public Nullable<decimal> po_ent_ex { get; set; }
        public Nullable<System.DateTime> po_tax_date { get; set; }
        public string po_fsm_type { get; set; }
        public string po_bank { get; set; }
        public string po_pr_list { get; set; }
        public string po_tax_env { get; set; }
        public Nullable<bool> po_sched { get; set; }
        public string po_pr_list2 { get; set; }
        public string po_tax_usage { get; set; }
        public Nullable<bool> po_fix_pr { get; set; }
        public string po_taxc { get; set; }
        public string po_sch_mthd { get; set; }
        public Nullable<System.DateTime> po_priced_dt { get; set; }
        public Nullable<System.DateTime> po_pricing_dt { get; set; }
        public string po_ers_opt { get; set; }
        public Nullable<int> po_pr_lst_tp { get; set; }
        public string po__qadc01 { get; set; }
        public string po__qadc02 { get; set; }
        public Nullable<decimal> po__qadd01 { get; set; }
        public Nullable<decimal> po__qadd02 { get; set; }
        public Nullable<int> po__qadi01 { get; set; }
        public Nullable<int> po__qadi02 { get; set; }
        public string po_so_nbr { get; set; }
        public bool po_is_btb { get; set; }
        public bool po_so_hold { get; set; }
        public string po_xmit { get; set; }
        public decimal po_ex_rate2 { get; set; }
        public string po_ex_ratetype { get; set; }
        public int po_exru_seq { get; set; }
        public string po_ap_sub { get; set; }
        public Nullable<decimal> po_crt_int { get; set; }
        public bool po_consignment { get; set; }
        public int po_max_aging_days { get; set; }
        public string po_app_owner { get; set; }
        public string po_tot_terms_code { get; set; }
        public decimal po_translt_days { get; set; }
        public string po_domain { get; set; }
        public decimal oid_po_mstr { get; set; }
    }
}
