//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class pod_det1
    {
        public string pod_nbr { get; set; }
        public Nullable<System.DateTime> pod_due_date { get; set; }
        public Nullable<int> pod_line { get; set; }
        public string pod_part { get; set; }
        public Nullable<decimal> pod_qty_ord { get; set; }
        public Nullable<decimal> pod_qty_rcvd { get; set; }
        public Nullable<decimal> pod_pur_cost { get; set; }
        public Nullable<decimal> pod_std_cost { get; set; }
        public string pod_so_job { get; set; }
        public Nullable<decimal> pod_qty_chg { get; set; }
        public Nullable<decimal> pod_cost_chg { get; set; }
        public Nullable<decimal> pod_bo_chg { get; set; }
        public string pod_acct { get; set; }
        public Nullable<System.DateTime> pod_per_date { get; set; }
        public string pod_type { get; set; }
        public Nullable<bool> pod_insp_rqd { get; set; }
        public string pod_wo_lot { get; set; }
        public string pod_vpart { get; set; }
        public Nullable<System.DateTime> pod_need { get; set; }
        public Nullable<bool> pod_taxable { get; set; }
        public string pod_desc { get; set; }
        public string pod_cc { get; set; }
        public string pod__qad04 { get; set; }
        public string pod_um { get; set; }
        public Nullable<decimal> pod_disc_pct { get; set; }
        public string pod_req_nbr { get; set; }
        public string pod__qad10 { get; set; }
        public Nullable<decimal> pod_um_conv { get; set; }
        public string pod_loc { get; set; }
        public string pod_serial { get; set; }
        public Nullable<int> pod_op { get; set; }
        public string pod_contract { get; set; }
        public string pod_status { get; set; }
        public string pod_rev { get; set; }
        public Nullable<int> pod_cmtindx { get; set; }
        public Nullable<int> pod_req_line { get; set; }
        public string pod_project { get; set; }
        public Nullable<decimal> pod_ps_chg { get; set; }
        public Nullable<bool> pod_cst_up { get; set; }
        public string pod_rum { get; set; }
        public string pod_user1 { get; set; }
        public string pod_user2 { get; set; }
        public Nullable<bool> pod_vat { get; set; }
        public string pod__qad16 { get; set; }
        public string pod__qad06 { get; set; }
        public Nullable<bool> pod_pst { get; set; }
        public Nullable<bool> pod__qad13 { get; set; }
        public string pod__qad07 { get; set; }
        public string pod_pay_um { get; set; }
        public Nullable<decimal> pod_pum_conv { get; set; }
        public Nullable<bool> pod__qad15 { get; set; }
        public string pod_site { get; set; }
        public Nullable<decimal> pod_rum_conv { get; set; }
        public Nullable<decimal> pod_qty_rtnd { get; set; }
        public string pod_blanket { get; set; }
        public Nullable<int> pod_blnkt_ln { get; set; }
        public Nullable<System.DateTime> pod__qad01 { get; set; }
        public Nullable<int> pod__qad02 { get; set; }
        public string pod__qad03 { get; set; }
        public Nullable<bool> pod__qad05 { get; set; }
        public Nullable<System.DateTime> pod__qad08 { get; set; }
        public Nullable<int> pod__qad09 { get; set; }
        public string pod__qad11 { get; set; }
        public Nullable<bool> pod__qad12 { get; set; }
        public Nullable<System.DateTime> pod__qad14 { get; set; }
        public Nullable<int> pod_rel_nbr { get; set; }
        public Nullable<decimal> pod_rel_qty { get; set; }
        public string pod_reason { get; set; }
        public string pod_request { get; set; }
        public string pod_approve { get; set; }
        public string pod__chr01 { get; set; }
        public string pod__chr02 { get; set; }
        public string pod__chr03 { get; set; }
        public string pod__chr04 { get; set; }
        public string pod__chr05 { get; set; }
        public string pod__chr06 { get; set; }
        public string pod__chr07 { get; set; }
        public string pod__chr08 { get; set; }
        public string pod__chr09 { get; set; }
        public string pod__chr10 { get; set; }
        public Nullable<System.DateTime> pod__dte01 { get; set; }
        public Nullable<System.DateTime> pod__dte02 { get; set; }
        public Nullable<decimal> pod__dec01 { get; set; }
        public Nullable<decimal> pod__dec02 { get; set; }
        public Nullable<bool> pod__log01 { get; set; }
        public Nullable<decimal> pod_tax_max { get; set; }
        public string pod_curr_rlse_id { get; set; }
        public Nullable<bool> pod_sched { get; set; }
        public string pod_cum_qty { get; set; }
        public string pod_cum_date { get; set; }
        public string pod_contr_id { get; set; }
        public string pod_apr_code { get; set; }
        public string pod_taxc { get; set; }
        public string pod_rma_type { get; set; }
        public string pod_po_site { get; set; }
        public string pod_po_db { get; set; }
        public Nullable<int> pod_firm_weeks { get; set; }
        public Nullable<decimal> pod_mrp_pct { get; set; }
        public Nullable<int> pod_raw_weeks { get; set; }
        public Nullable<int> pod_fab_weeks { get; set; }
        public Nullable<int> pod_ship_weeks { get; set; }
        public Nullable<int> pod_plan_weeks { get; set; }
        public Nullable<decimal> pod_translt_days { get; set; }
        public string pod_fsm_type { get; set; }
        public string pod_sd_pat { get; set; }
        public string pod_sd_time { get; set; }
        public Nullable<decimal> pod_ord_mult { get; set; }
        public string pod_pkg_code { get; set; }
        public Nullable<bool> pod_sch_mrp { get; set; }
        public string pod_sch_data { get; set; }
        public Nullable<int> pod_rlse_nbr { get; set; }
        public Nullable<int> pod_plan_days { get; set; }
        public Nullable<int> pod_plan_mths { get; set; }
        public Nullable<int> pod_firm_days { get; set; }
        public string pod_start_eff { get; set; }
        public string pod_end_eff { get; set; }
        public Nullable<int> pod_raw_days { get; set; }
        public Nullable<int> pod_fab_days { get; set; }
        public string pod_tax_usage { get; set; }
        public Nullable<bool> pod_tax_in { get; set; }
        public Nullable<bool> pod_sched_chgd { get; set; }
        public string pod_pr_list { get; set; }
        public string pod_dock { get; set; }
        public string pod_pastdue { get; set; }
        public Nullable<bool> pod_fix_pr { get; set; }
        public string pod_drp_ref { get; set; }
        public string pod_tax_env { get; set; }
        public Nullable<decimal> pod_crt_int { get; set; }
        public string pod_fr_list { get; set; }
        public Nullable<decimal> pod_translt_hrs { get; set; }
        public Nullable<decimal> pod_sftylt_days { get; set; }
        public Nullable<decimal> pod_sftylt_hrs { get; set; }
        public string pod_lot_next { get; set; }
        public Nullable<bool> pod_lot_rcpt { get; set; }
        public string pod_grade { get; set; }
        public Nullable<System.DateTime> pod_expire { get; set; }
        public string pod_rctstat { get; set; }
        public Nullable<decimal> pod_assay { get; set; }
        public Nullable<bool> pod_rctstat_active { get; set; }
        public Nullable<System.DateTime> pod_pricing_dt { get; set; }
        public Nullable<int> pod_pr_lst_tp { get; set; }
        public Nullable<int> pod_ers_opt { get; set; }
        public Nullable<decimal> pod__qadd01 { get; set; }
        public Nullable<decimal> pod__qadd02 { get; set; }
        public Nullable<decimal> pod__qadd03 { get; set; }
        public int pod_sod_line { get; set; }
        public string pod_so_status { get; set; }
        public Nullable<System.DateTime> pod_sub_ship_date { get; set; }
        public string pod_sub_type { get; set; }
        public string pod_sub { get; set; }
        public string pod_wip_lotser { get; set; }
        public int pod_pjs_line { get; set; }
        public bool pod_consignment { get; set; }
        public int pod_max_aging_days { get; set; }
        public bool pod_multi_due_dates { get; set; }
        public string pod_domain { get; set; }
        public decimal oid_pod_det { get; set; }
    }
}
