//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public string PrinterName { get; set; }
        public string Port { get; set; }
        public string IPAddress { get; set; }
        public bool Active { get; set; }
    }
}
