//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_mstr
    {
        public string ps_par { get; set; }
        public string ps_comp { get; set; }
        public string ps_ref { get; set; }
        public Nullable<decimal> ps_qty_per { get; set; }
        public Nullable<decimal> ps_scrp_pct { get; set; }
        public string ps_ps_code { get; set; }
        public Nullable<int> ps_lt_off { get; set; }
        public System.DateTime ps_start { get; set; }
        public Nullable<System.DateTime> ps_end { get; set; }
        public string ps_rmks { get; set; }
        public Nullable<int> ps_op { get; set; }
        public Nullable<int> ps_item_no { get; set; }
        public Nullable<bool> ps_mandatory { get; set; }
        public Nullable<bool> ps_exclusive { get; set; }
        public string ps_process { get; set; }
        public string ps_qty_type { get; set; }
        public string ps_user1 { get; set; }
        public string ps_user2 { get; set; }
        public Nullable<decimal> ps_fcst_pct { get; set; }
        public Nullable<bool> ps_default { get; set; }
        public string ps_group { get; set; }
        public Nullable<bool> ps_critical { get; set; }
        public Nullable<decimal> ps_qty_per_b { get; set; }
        public decimal ps_assay { get; set; }
        public string ps_comm_code { get; set; }
        public string ps_comp_um { get; set; }
        public decimal ps_um_conv { get; set; }
        public string ps_userid { get; set; }
        public Nullable<System.DateTime> ps_mod_date { get; set; }
        public Nullable<bool> ps__qad01 { get; set; }
        public Nullable<bool> ps_non_bal { get; set; }
        public Nullable<decimal> ps_batch_pct { get; set; }
        public Nullable<int> ps_cmtindx { get; set; }
        public string ps_start_ecn { get; set; }
        public string ps_end_ecn { get; set; }
        public string ps_joint_type { get; set; }
        public decimal ps_cop_qty { get; set; }
        public decimal ps_cst_pct { get; set; }
        public Nullable<decimal> ps_prod_pct { get; set; }
        public Nullable<decimal> ps_qty_cons { get; set; }
        public Nullable<decimal> ps_qty_exch { get; set; }
        public Nullable<decimal> ps_qty_diag { get; set; }
    }
}
