//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class pt_mstr_extra
    {
        public string pt_part { get; set; }
        public string mcCode { get; set; }
        public string vsCode { get; set; }
        public string svsCode { get; set; }
        public Nullable<int> FoodExperience { get; set; }
        public string gtin13 { get; set; }
        public string gtin14 { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public string CslReportingGroup { get; set; }
    
        public virtual pt_mstr pt_mstr { get; set; }
    }
}
