//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class pt_mstr_manual
    {
        public string pt_part { get; set; }
        public string pt_desc1 { get; set; }
        public string pt_desc2 { get; set; }
        public string pt_um { get; set; }
        public string pt_prod_line { get; set; }
        public string pt_group { get; set; }
        public string pt_part_type { get; set; }
        public string pt_status { get; set; }
        public Nullable<decimal> pt_size { get; set; }
        public string pt_drwg_size { get; set; }
        public string pt_dsgn_grp { get; set; }
        public string mcCode { get; set; }
        public string vsCode { get; set; }
        public string svsCode { get; set; }
        public Nullable<int> FoodExperience { get; set; }
        public string gtin13 { get; set; }
        public string gtin14 { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
    }
}
