//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptp_det
    {
        public string ptp_part { get; set; }
        public string ptp_site { get; set; }
        public Nullable<decimal> ptp_batch { get; set; }
        public string ptp_bom_code { get; set; }
        public string ptp_buyer { get; set; }
        public Nullable<int> ptp_cum_lead { get; set; }
        public Nullable<int> ptp_ins_lead { get; set; }
        public Nullable<bool> ptp_ins_rqd { get; set; }
        public Nullable<bool> ptp_iss_pol { get; set; }
        public Nullable<decimal> ptp_mfg_lead { get; set; }
        public Nullable<bool> ptp_ms { get; set; }
        public Nullable<decimal> ptp_ord_max { get; set; }
        public Nullable<decimal> ptp_ord_min { get; set; }
        public Nullable<decimal> ptp_ord_mult { get; set; }
        public Nullable<int> ptp_ord_per { get; set; }
        public string ptp_ord_pol { get; set; }
        public Nullable<decimal> ptp_ord_qty { get; set; }
        public Nullable<bool> ptp_phantom { get; set; }
        public Nullable<bool> ptp_plan_ord { get; set; }
        public string ptp_pm_code { get; set; }
        public Nullable<int> ptp_pur_lead { get; set; }
        public string ptp_rev { get; set; }
        public Nullable<decimal> ptp_rop { get; set; }
        public string ptp_routing { get; set; }
        public Nullable<decimal> ptp_run { get; set; }
        public Nullable<decimal> ptp_run_ll { get; set; }
        public Nullable<decimal> ptp_setup { get; set; }
        public Nullable<decimal> ptp_setup_ll { get; set; }
        public Nullable<decimal> ptp_sfty_stk { get; set; }
        public Nullable<decimal> ptp_sfty_tme { get; set; }
        public Nullable<int> ptp_timefnce { get; set; }
        public string ptp_user1 { get; set; }
        public string ptp_user2 { get; set; }
        public string ptp_vend { get; set; }
        public Nullable<decimal> ptp_yld_pct { get; set; }
        public Nullable<decimal> ptp_assay { get; set; }
        public string ptp_grade { get; set; }
        public string ptp_network { get; set; }
        public System.DateTime ptp_added { get; set; }
        public string ptp_draw { get; set; }
        public bool ptp_eco_pend { get; set; }
        public int ptp_ll_bom { get; set; }
        public bool ptp_rollup { get; set; }
        public string ptp_trantype { get; set; }
        public int ptp_ll_drp { get; set; }
        public string ptp_po_site { get; set; }
        public string ptp_userid { get; set; }
        public Nullable<System.DateTime> ptp_mod_date { get; set; }
        public string ptp_rollup_id { get; set; }
        public Nullable<decimal> ptp_mfg_pct { get; set; }
        public Nullable<decimal> ptp_pur_pct { get; set; }
        public Nullable<decimal> ptp_drp_pct { get; set; }
        public string ptp_pou_code { get; set; }
        public Nullable<decimal> ptp_wks_avg { get; set; }
        public Nullable<decimal> ptp_wks_max { get; set; }
        public Nullable<decimal> ptp_wks_min { get; set; }
        public Nullable<int> ptp_pick_logic { get; set; }
        public string ptp_joint_type { get; set; }
        public string ptp_btb_type { get; set; }
        public string ptp_cfg_type { get; set; }
        public Nullable<bool> ptp_op_yield { get; set; }
        public string ptp_run_seq1 { get; set; }
        public string ptp_run_seq2 { get; set; }
        public string ptp_atp_enforcement { get; set; }
        public bool ptp_atp_family { get; set; }
    }
}
