//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvo_mstr
    {
        public int pvo_id { get; set; }
        public string pvo_buyer { get; set; }
        public string pvo_lc_charge { get; set; }
        public string pvo_supplier { get; set; }
        public string pvo_internal_ref_type { get; set; }
        public string pvo_internal_ref { get; set; }
        public string pvo_external_ref { get; set; }
        public Nullable<System.DateTime> pvo_trans_date { get; set; }
        public Nullable<System.DateTime> pvo_eff_date { get; set; }
        public string pvo_last_voucher { get; set; }
        public string pvo_shipto { get; set; }
        public string pvo_order_type { get; set; }
        public string pvo_order { get; set; }
        public Nullable<int> pvo_line { get; set; }
        public string pvo_part { get; set; }
        public Nullable<decimal> pvo_trans_qty { get; set; }
        public Nullable<decimal> pvo_vouchered_qty { get; set; }
        public Nullable<System.DateTime> pvo_mod_date { get; set; }
    }
}
