//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvod_det
    {
        public int pvod_id { get; set; }
        public int pvod_id_line { get; set; }
        public string pvod_order_type { get; set; }
        public string pvod_order { get; set; }
        public int pvod_order_line { get; set; }
        public string pvod_internal_ref { get; set; }
        public string pvod_internal_ref_type { get; set; }
        public string pvod_part { get; set; }
        public string pvod_shipto { get; set; }
    }
}
