//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QADLiveEntities : DbContext
    {
        public QADLiveEntities()
            : base("name=QADLiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ac_mstr> ac_mstr { get; set; }
        public virtual DbSet<acd_det> acd_det { get; set; }
        public virtual DbSet<ad_mstr> ad_mstr { get; set; }
        public virtual DbSet<ad_mstr_extra> ad_mstr_extra { get; set; }
        public virtual DbSet<ad_mstr_manual> ad_mstr_manual { get; set; }
        public virtual DbSet<ap_mstr> ap_mstr { get; set; }
        public virtual DbSet<ar_mstr> ar_mstr { get; set; }
        public virtual DbSet<ard_det> ard_det { get; set; }
        public virtual DbSet<bgd_det> bgd_det { get; set; }
        public virtual DbSet<Cube2015_Fact_Yield> Cube2015_Fact_Yield { get; set; }
        public virtual DbSet<Fact_SalesECSL24> Fact_SalesECSL24 { get; set; }
        public virtual DbSet<Fact_SalesECSL48> Fact_SalesECSL48 { get; set; }
        public virtual DbSet<Fact_SalesRC> Fact_SalesRC { get; set; }
        public virtual DbSet<Fact_SalesRC_Comments> Fact_SalesRC_Comments { get; set; }
        public virtual DbSet<Fact_SalesRC_CommentsInfo> Fact_SalesRC_CommentsInfo { get; set; }
        public virtual DbSet<FormtrapPrinter_> FormtrapPrinter_ { get; set; }
        public virtual DbSet<ps_mstr> ps_mstr { get; set; }
        public virtual DbSet<pt_mstr> pt_mstr { get; set; }
        public virtual DbSet<pt_mstr_extra> pt_mstr_extra { get; set; }
        public virtual DbSet<pt_mstr_manual> pt_mstr_manual { get; set; }
        public virtual DbSet<ptp_det> ptp_det { get; set; }
        public virtual DbSet<ro_det> ro_det { get; set; }
        public virtual DbSet<rsn_ref> rsn_ref { get; set; }
        public virtual DbSet<rsn_ref_manual> rsn_ref_manual { get; set; }
        public virtual DbSet<si_mstr> si_mstr { get; set; }
        public virtual DbSet<si_mstr_extra> si_mstr_extra { get; set; }
        public virtual DbSet<sys_acl> sys_acl { get; set; }
        public virtual DbSet<sys_countries> sys_countries { get; set; }
        public virtual DbSet<sys_distributionCentres> sys_distributionCentres { get; set; }
        public virtual DbSet<sys_marketing> sys_marketing { get; set; }
        public virtual DbSet<sys_partnercodes> sys_partnercodes { get; set; }
        public virtual DbSet<sys_partnersubcodes> sys_partnersubcodes { get; set; }
        public virtual DbSet<sys_regions> sys_regions { get; set; }
        public virtual DbSet<sys_states> sys_states { get; set; }
        public virtual DbSet<sys_subvaluestreams> sys_subvaluestreams { get; set; }
        public virtual DbSet<sys_valuestreams> sys_valuestreams { get; set; }
        public virtual DbSet<sys_zones> sys_zones { get; set; }
        public virtual DbSet<tblChepProduct> tblChepProducts { get; set; }
        public virtual DbSet<tblDIFFOTOutbound> tblDIFFOTOutbounds { get; set; }
        public virtual DbSet<tblLabelMessage> tblLabelMessages { get; set; }
        public virtual DbSet<tblSmartBuy> tblSmartBuys { get; set; }
        public virtual DbSet<tr_hist> tr_hist { get; set; }
        public virtual DbSet<trgl_det> trgl_det { get; set; }
        public virtual DbSet<vo_mstr> vo_mstr { get; set; }
        public virtual DbSet<vod_det> vod_det { get; set; }
        public virtual DbSet<vph_hist> vph_hist { get; set; }
        public virtual DbSet<wc_mstr> wc_mstr { get; set; }
        public virtual DbSet<Yield> Yields { get; set; }
        public virtual DbSet<DetailedOld> DetailedOlds { get; set; }
        public virtual DbSet<DetailedTemp> DetailedTemps { get; set; }
        public virtual DbSet<SupplierTimeTolerance> SupplierTimeTolerances { get; set; }
        public virtual DbSet<ar_mstr_audit> ar_mstr_audit { get; set; }
        public virtual DbSet<asc_mstr> asc_mstr { get; set; }
        public virtual DbSet<AutoPoSupplierGrouping> AutoPoSupplierGroupings { get; set; }
        public virtual DbSet<ba_mstr> ba_mstr { get; set; }
        public virtual DbSet<cm_mstr> cm_mstr { get; set; }
        public virtual DbSet<FinancialCalendar> FinancialCalendars { get; set; }
        public virtual DbSet<glc_cal> glc_cal { get; set; }
        public virtual DbSet<gltr_hist_audit> gltr_hist_audit { get; set; }
        public virtual DbSet<idh_hist> idh_hist { get; set; }
        public virtual DbSet<idh_hist_audit> idh_hist_audit { get; set; }
        public virtual DbSet<ih_hist> ih_hist { get; set; }
        public virtual DbSet<ih_hist_audit> ih_hist_audit { get; set; }
        public virtual DbSet<in_mstr> in_mstr { get; set; }
        public virtual DbSet<ld_det> ld_det { get; set; }
        public virtual DbSet<ln_mstr> ln_mstr { get; set; }
        public virtual DbSet<mrp_det> mrp_det { get; set; }
        public virtual DbSet<pl_mstr> pl_mstr { get; set; }
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<pvo_mstr> pvo_mstr { get; set; }
        public virtual DbSet<pvod_det> pvod_det { get; set; }
        public virtual DbSet<ReceivalsLocationPo> ReceivalsLocationPoes { get; set; }
        public virtual DbSet<sod_det> sod_det { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblWetSalad> tblWetSalads { get; set; }
        public virtual DbSet<usr_mstr> usr_mstr { get; set; }
        public virtual DbSet<usrg_mstr> usrg_mstr { get; set; }
        public virtual DbSet<usrgd_det> usrgd_det { get; set; }
        public virtual DbSet<wc_mstr_manual> wc_mstr_manual { get; set; }
        public virtual DbSet<wo_mstr> wo_mstr { get; set; }
        public virtual DbSet<wod_det> wod_det { get; set; }
        public virtual DbSet<Detailed> Detaileds { get; set; }
        public virtual DbSet<po_mstr> po_mstr { get; set; }
        public virtual DbSet<pod_det1> pod_det1 { get; set; }
        public virtual DbSet<pt_mstr1> pt_mstr1 { get; set; }
        public virtual DbSet<vd_mstr1> vd_mstr1 { get; set; }
    }
}
