//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reason
    {
        public string ReasonCode { get; set; }
        public string ReasonDesc { get; set; }
        public string ReasonType { get; set; }
        public bool Active { get; set; }
        public string UserID { get; set; }
        public string RockyTypeMatch { get; set; }
    }
}
