//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivalsLocationPo
    {
        public string ld_site { get; set; }
        public string ld_part { get; set; }
        public decimal ld_qty_oh { get; set; }
        public string ld_loc { get; set; }
        public string ld_lot { get; set; }
        public string ld_ref { get; set; }
        public string ld_status { get; set; }
        public Nullable<System.DateTime> ld_date { get; set; }
        public Nullable<System.DateTime> ld_expire { get; set; }
        public Nullable<decimal> in_qty_oh { get; set; }
        public string tr_addr { get; set; }
        public string tr_nbr { get; set; }
    }
}
