//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_det
    {
        public string ro_routing { get; set; }
        public int ro_op { get; set; }
        public string ro_desc { get; set; }
        public string ro_wkctr { get; set; }
        public Nullable<decimal> ro_run { get; set; }
        public System.DateTime ro_start { get; set; }
        public Nullable<System.DateTime> ro_end { get; set; }
        public Nullable<decimal> ro_cyc_rate { get; set; }
    }
}
