//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_det
    {
        public string rpt_sys { get; set; }
        public string rpt_id { get; set; }
        public int rpt_not_id { get; set; }
        public string rpt_not_username { get; set; }
        public string rpt_not_email { get; set; }
        public string rpt_not_sms { get; set; }
        public Nullable<bool> active { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
