//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class rsn_ref_manual
    {
        public string rsn_code { get; set; }
        public string rsn_type { get; set; }
        public string rsn_desc { get; set; }
        public string rsn_user1 { get; set; }
        public string rsn_user2 { get; set; }
        public string rsn__qadc01 { get; set; }
    }
}
