//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SafetyManagementSystemEntities : DbContext
    {
        public SafetyManagementSystemEntities()
            : base("name=SafetyManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vFormStatu> vFormStatus { get; set; }
        public virtual DbSet<vFormStatusWithSafetyAction> vFormStatusWithSafetyActions { get; set; }
        public virtual DbSet<vHazardReport> vHazardReports { get; set; }
        public virtual DbSet<vIncidentAccident> vIncidentAccidents { get; set; }
        public virtual DbSet<vIncidentsByDay> vIncidentsByDays { get; set; }
        public virtual DbSet<vInspectionAudit> vInspectionAudits { get; set; }
        public virtual DbSet<vJseaRiskAssessments_> vJseaRiskAssessments_ { get; set; }
        public virtual DbSet<vRiskAssessment> vRiskAssessments { get; set; }
        public virtual DbSet<vSafetyAction> vSafetyActions { get; set; }
        public virtual DbSet<vSafetyActionsByMonthBySite> vSafetyActionsByMonthBySites { get; set; }
        public virtual DbSet<vSafetyActionsByMonthByUser> vSafetyActionsByMonthByUsers { get; set; }
        public virtual DbSet<vSafetyActionsThisMonthByUser> vSafetyActionsThisMonthByUsers { get; set; }
        public virtual DbSet<vSafetyWalkTalk> vSafetyWalkTalks { get; set; }
        public virtual DbSet<vSafetyWalkTalksByDay> vSafetyWalkTalksByDays { get; set; }
        public virtual DbSet<vIncidentsByMonth> vIncidentsByMonths { get; set; }
        public virtual DbSet<vIncidentsByWeek> vIncidentsByWeeks { get; set; }
        public virtual DbSet<vSafetyWalkTalksByMonth> vSafetyWalkTalksByMonths { get; set; }
        public virtual DbSet<vSafetyWalkTalksByWeek> vSafetyWalkTalksByWeeks { get; set; }
    }
}
