//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class si_mstr_extra
    {
        public string si_site { get; set; }
        public bool isAvailableCSL { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdOn { get; set; }
        public string updatedBy { get; set; }
        public System.DateTime updatedOn { get; set; }
    }
}
