//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site()
        {
            this.ApprovalList = new HashSet<ApprovalList>();
            this.GLCodeMapping = new HashSet<GLCodeMapping>();
        }
    
        public string SiteID { get; set; }
        public string SiteName { get; set; }
        public Nullable<bool> ManualEntryAutoApprove { get; set; }
        public Nullable<decimal> TimeInterval { get; set; }
        public Nullable<decimal> MealInterval { get; set; }
        public Nullable<bool> UseApprovalList { get; set; }
        public Nullable<int> PreloadDate { get; set; }
        public string EntityID { get; set; }
        public Nullable<int> NextEmployeeNumber { get; set; }
        public Nullable<bool> ModifyEmployeeList { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalList> ApprovalList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLCodeMapping> GLCodeMapping { get; set; }
    }
}
