//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBudgetHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBudgetHeader()
        {
            this.tblBudgetDetails = new HashSet<tblBudgetDetail>();
        }
    
        public int BudgetID { get; set; }
        public string BudgetSet { get; set; }
        public decimal TargetBudget { get; set; }
        public Nullable<bool> AllowEdit { get; set; }
        public Nullable<bool> AllowReport { get; set; }
        public bool Active { get; set; }
        public string UserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBudgetDetail> tblBudgetDetails { get; set; }
    }
}
