//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBudgetDetail
    {
        public int BudgetLineID { get; set; }
        public int BudgetID { get; set; }
        public int EntityCCAccID { get; set; }
        public string CalendarYear { get; set; }
        public string CalendarPeriod { get; set; }
        public decimal Amount { get; set; }
        public bool Active { get; set; }
        public string UserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual tblBudgetHeader tblBudgetHeader { get; set; }
    }
}
