//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCapexRouting
    {
        public int id { get; set; }
        public int costCentre { get; set; }
        public int limit { get; set; }
        public string approver1 { get; set; }
        public string approver2 { get; set; }
        public string approver3 { get; set; }
        public string approver4 { get; set; }
        public string approver5 { get; set; }
        public string approver6 { get; set; }
        public string approver7 { get; set; }
        public string approver8 { get; set; }
        public string approver9 { get; set; }
        public string approver10 { get; set; }
        public bool active { get; set; }
        public System.DateTime updated { get; set; }
        public string updatedBy { get; set; }
        public System.DateTime created { get; set; }
        public string createdBy { get; set; }
    }
}
