//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDIFFOTOutbound
    {
        public int DIFFOTID { get; set; }
        public string Site { get; set; }
        public System.DateTime DIFFOTDate { get; set; }
        public double DIFScore { get; set; }
        public double OTScore { get; set; }
        public double OSLScore { get; set; }
        public double RecipeChangeScore { get; set; }
        public double ComDecScore { get; set; }
        public double FPtoSpecScore { get; set; }
        public bool Active { get; set; }
        public string UserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    }
}
