//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntityCCAcc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEntityCCAcc()
        {
            this.tblPODetails = new HashSet<tblPODetail>();
            this.tblRoutingAccountLimits = new HashSet<tblRoutingAccountLimit>();
        }
    
        public int EntityCCAccID { get; set; }
        public int EntityID { get; set; }
        public int CostCentreID { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> SubAccountID { get; set; }
        public Nullable<bool> AllowToRaisePO { get; set; }
        public bool Active { get; set; }
        public string UserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblCostCentre tblCostCentre { get; set; }
        public virtual tblEntity tblEntity { get; set; }
        public virtual tblSubAccount tblSubAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPODetail> tblPODetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoutingAccountLimit> tblRoutingAccountLimits { get; set; }
    }
}
