//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPODetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPODetail()
        {
            this.tblPOPhasings = new HashSet<tblPOPhasing>();
        }
    
        public int POLineID { get; set; }
        public int POID { get; set; }
        public int LineNumber { get; set; }
        public int Revision { get; set; }
        public string SupplierPartNo { get; set; }
        public string Details { get; set; }
        public int EntityCCAccID { get; set; }
        public Nullable<int> CapexID { get; set; }
        public double QuantityOrdered { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal GSTAmount { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public double QuantityOpen { get; set; }
        public Nullable<bool> EstimateOnly { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string BlockID { get; set; }
        public string AssetID { get; set; }
        public int Status { get; set; }
        public bool OverBudget { get; set; }
        public Nullable<bool> BudgetItem { get; set; }
        public Nullable<bool> HDPlanItem { get; set; }
        public bool Active { get; set; }
        public string UserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual tblCapex tblCapex { get; set; }
        public virtual tblEntityCCAcc tblEntityCCAcc { get; set; }
        public virtual tblPOHeader tblPOHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOPhasing> tblPOPhasings { get; set; }
    }
}
