//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoutingList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRoutingList()
        {
            this.tblRoutingTables = new HashSet<tblRoutingTable>();
        }
    
        public int ListID { get; set; }
        public int LimitID { get; set; }
        public string AuthoriserName { get; set; }
        public int ApprovalType { get; set; }
        public int ApprovalNumber { get; set; }
        public bool Active { get; set; }
        public string UserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual tblRoutingAccountLimit tblRoutingAccountLimit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoutingTable> tblRoutingTables { get; set; }
    }
}
