//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStagingAccCC
    {
        public System.Guid StagingAccCCID { get; set; }
        public string AccountCode { get; set; }
        public int StagingCostCentreID { get; set; }
        public bool Active { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual tblStagingCostCentresDEV tblStagingCostCentresDEV { get; set; }
    }
}
