//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStagingAccount
    {
        public string Account { get; set; }
        public string Description { get; set; }
        public string C130 { get; set; }
        public string C135 { get; set; }
        public string C136 { get; set; }
        public string C137 { get; set; }
        public string C145 { get; set; }
        public string C161 { get; set; }
        public string C162 { get; set; }
        public string C165 { get; set; }
        public string C167 { get; set; }
        public string C230 { get; set; }
        public string C235 { get; set; }
        public string C245 { get; set; }
        public string C246 { get; set; }
        public string C251 { get; set; }
        public string C252 { get; set; }
        public string C253 { get; set; }
        public string C254 { get; set; }
        public string C261 { get; set; }
        public string C262 { get; set; }
        public string C265 { get; set; }
        public string C267 { get; set; }
        public string C275 { get; set; }
        public string C276 { get; set; }
        public string C310 { get; set; }
        public string C320 { get; set; }
        public string C351 { get; set; }
        public string C352 { get; set; }
        public string C353 { get; set; }
        public string C354 { get; set; }
        public string C355 { get; set; }
        public string C361 { get; set; }
        public string C362 { get; set; }
        public string C365 { get; set; }
        public string C367 { get; set; }
        public string C370 { get; set; }
        public string C375 { get; set; }
        public string C376 { get; set; }
        public string C410 { get; set; }
        public string C420 { get; set; }
        public string C435 { get; set; }
        public string C445 { get; set; }
        public string C446 { get; set; }
        public string C451 { get; set; }
        public string C452 { get; set; }
        public string C453 { get; set; }
        public string C454 { get; set; }
        public string C455 { get; set; }
        public string C461 { get; set; }
        public string C462 { get; set; }
        public string C465 { get; set; }
        public string C467 { get; set; }
        public string C470 { get; set; }
        public string C475 { get; set; }
        public string C476 { get; set; }
        public string C510 { get; set; }
        public string C520 { get; set; }
        public string C545 { get; set; }
        public string C551 { get; set; }
        public string C552 { get; set; }
        public string C553 { get; set; }
        public string C554 { get; set; }
        public string C555 { get; set; }
        public string C561 { get; set; }
        public string C562 { get; set; }
        public string C565 { get; set; }
        public string C567 { get; set; }
        public string C570 { get; set; }
        public string C575 { get; set; }
        public string C576 { get; set; }
        public string C7001 { get; set; }
        public string C7003 { get; set; }
        public string C7005 { get; set; }
        public string C7006 { get; set; }
        public string C7008 { get; set; }
        public string C7009 { get; set; }
        public string C7101 { get; set; }
        public string C7103 { get; set; }
        public string C7105 { get; set; }
        public string C7108 { get; set; }
        public string C7199 { get; set; }
        public string C7201 { get; set; }
        public string C7202 { get; set; }
        public string C7203 { get; set; }
        public string C7204 { get; set; }
        public string C7207 { get; set; }
        public string C7208 { get; set; }
        public string C7210 { get; set; }
        public string C7299 { get; set; }
        public string C7310 { get; set; }
        public string C7311 { get; set; }
        public string C7312 { get; set; }
        public string C7313 { get; set; }
        public string C7314 { get; set; }
        public string C7399 { get; set; }
        public string C7408 { get; set; }
        public string C7585 { get; set; }
        public string C7680 { get; set; }
        public string C7935 { get; set; }
        public string C7936 { get; set; }
        public string C7945 { get; set; }
        public string C7946 { get; set; }
        public string C7950 { get; set; }
        public string C7960 { get; set; }
        public string C7965 { get; set; }
        public string C7970 { get; set; }
        public string C7975 { get; set; }
        public string C7979 { get; set; }
        public string C7990 { get; set; }
        public string C910 { get; set; }
        public string C1110 { get; set; }
        public string C1210 { get; set; }
        public string C1310 { get; set; }
        public string C965 { get; set; }
        public string C1065 { get; set; }
        public string C1165 { get; set; }
        public string C1265 { get; set; }
        public string C1365 { get; set; }
        public string C635 { get; set; }
        public string C735 { get; set; }
        public string C755 { get; set; }
        public string C151 { get; set; }
        public string C9999 { get; set; }
        public System.DateTime created { get; set; }
    }
}
