//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStagingEmployeesDEV
    {
        public int StagingEmpID { get; set; }
        public string Employee { get; set; }
        public string Manager { get; set; }
        public int Level { get; set; }
        public int isDeleted { get; set; }
    
        public virtual tblStagingLevel tblStagingLevel { get; set; }
    }
}
