//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int TransID { get; set; }
        public Nullable<int> RefID { get; set; }
        public string RefType { get; set; }
        public string Code { get; set; }
        public string FromValue { get; set; }
        public string ToValue { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
