//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserDefault
    {
        public int DefaultID { get; set; }
        public string DefaultUserID { get; set; }
        public int entityID { get; set; }
        public int CostCentreID { get; set; }
        public int DeliveryAddressID { get; set; }
        public int GroupID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    }
}
