//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWetSalad
    {
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public string Ingredients { get; set; }
        public string Advisory { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
