//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tic_ctrl
    {
        public string tic_type { get; set; }
        public int tic_devno { get; set; }
        public string tic_siteid { get; set; }
        public string tic_workcenter { get; set; }
        public Nullable<bool> tic_include { get; set; }
        public string tic_dept { get; set; }
        public string tic_paycode { get; set; }
    }
}
