//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tic_det
    {
        public string tic_site { get; set; }
        public string tic_paycode { get; set; }
        public string tic_paycodedesc { get; set; }
        public string tic_type { get; set; }
        public Nullable<bool> tic_active { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
