//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tid_det_roster_on
    {
        public int tid_recid { get; set; }
        public string tid_site { get; set; }
        public string tid_team { get; set; }
        public string tid_location { get; set; }
        public Nullable<int> tid_card { get; set; }
        public Nullable<System.DateTime> tid_date { get; set; }
        public string tid_type { get; set; }
        public string tid_empno { get; set; }
        public string tid_name { get; set; }
        public Nullable<System.DateTime> tid_scan_in { get; set; }
        public Nullable<System.DateTime> tid_scan_out { get; set; }
        public Nullable<System.DateTime> tid_start { get; set; }
        public Nullable<System.DateTime> tid_finish { get; set; }
        public Nullable<double> tid_meal { get; set; }
        public Nullable<double> tid_meal_corr { get; set; }
        public Nullable<double> tid_hours { get; set; }
        public Nullable<int> tid_status { get; set; }
        public string tid_approver { get; set; }
        public string tid_grade { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> POID { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
