//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tid_allowances
    {
        public int tid_recid { get; set; }
        public string tid_alcode { get; set; }
        public Nullable<decimal> tid_alunit { get; set; }
        public Nullable<int> tid_AllowanceType { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
