//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tit_users_new
    {
        public string SITEID { get; set; }
        public int SYSTEMNO { get; set; }
        public int DEVICENO { get; set; }
        public string DESCRIPTION { get; set; }
        public string CARDONLY { get; set; }
        public string LONGACCESS { get; set; }
        public string USERTRACE { get; set; }
        public string PRIVILEGED { get; set; }
        public Nullable<int> LST_DOOR { get; set; }
        public string LST_DOORSTR { get; set; }
        public Nullable<System.DateTime> LSTDR_TIME { get; set; }
        public Nullable<int> LSTDR_REGION { get; set; }
        public string LST_REGIONSTR { get; set; }
        public string PINCARDNO { get; set; }
        public Nullable<int> USERTYPE { get; set; }
        public byte[] PICTURE { get; set; }
        public string CARDLAYOUT { get; set; }
        public byte[] GROUPS { get; set; }
        public byte[] COMMENTS { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string POSITION1 { get; set; }
        public string DEPARTMENT { get; set; }
        public string PHONE { get; set; }
        public string EXTENSION { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public string STATUS { get; set; }
        public string MEMBER { get; set; }
        public string LAYOUTCODE { get; set; }
        public string TAG { get; set; }
        public Nullable<int> LST_CHALL { get; set; }
        public string LST_CHALLSTR { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
    }
}
