//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tit_departments
    {
        public string SITEID { get; set; }
        public int SYSTEMNO { get; set; }
        public int DEVICENO { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMMENTS { get; set; }
        public string CARDBACK { get; set; }
        public string CARDFRONT { get; set; }
        public string EmployeeType { get; set; }
        public System.DateTime UPDATED { get; set; }
    }
}
