//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tit_users_static_old
    {
        public int tusid { get; set; }
        public string siteid { get; set; }
        public Nullable<int> systemno { get; set; }
        public Nullable<int> deviceno { get; set; }
        public string member { get; set; }
        public string department { get; set; }
    }
}
