//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tit_alarm_from_tid_det_detailed
    {
        public string SITEID { get; set; }
        public Nullable<System.DateTime> ALARMDATE { get; set; }
        public Nullable<int> DEVNO { get; set; }
        public string TID_EMPNO { get; set; }
        public string USERNAME { get; set; }
        public Nullable<int> PROCESSED { get; set; }
        public Nullable<System.DateTime> tid_date { get; set; }
    }
}
