//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tit_alarm_test
    {
        public string SITEID { get; set; }
        public int SYSTEMNO { get; set; }
        public int ALARMNUMBER { get; set; }
        public int CHALLENGERNO { get; set; }
        public Nullable<System.DateTime> ALARMDATE { get; set; }
        public Nullable<int> DATA1 { get; set; }
        public Nullable<int> DATA2 { get; set; }
        public Nullable<int> DATA3 { get; set; }
        public Nullable<int> DATA4 { get; set; }
        public Nullable<int> DATA5 { get; set; }
        public Nullable<int> DATA6 { get; set; }
        public Nullable<int> DATA7 { get; set; }
        public Nullable<int> DATA8 { get; set; }
        public string CHALLNAME { get; set; }
        public Nullable<int> DEVNO { get; set; }
        public Nullable<int> DEVTYPE { get; set; }
        public Nullable<int> COLOR { get; set; }
        public string ALARMDETAILS { get; set; }
        public string DEVNAME { get; set; }
        public string USERNAME { get; set; }
        public Nullable<int> INTERNAL { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public Nullable<System.DateTime> ROUNDTIME { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> PROCESSED { get; set; }
    }
}
