//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tna_ctrl
    {
        public string ctr_code { get; set; }
        public int ctr_id { get; set; }
        public string ctr_text { get; set; }
        public string ctr_value { get; set; }
        public Nullable<int> ctr_sortorder { get; set; }
        public Nullable<bool> ctr_active { get; set; }
    }
}
