//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_hist
    {
        public string tr_part { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
        public Nullable<System.DateTime> tr_per_date { get; set; }
        public string tr_type { get; set; }
        public string tr_loc { get; set; }
        public Nullable<decimal> tr_loc_begin { get; set; }
        public Nullable<decimal> tr_begin_qoh { get; set; }
        public Nullable<decimal> tr_qty_req { get; set; }
        public Nullable<decimal> tr_qty_chg { get; set; }
        public Nullable<decimal> tr_qty_short { get; set; }
        public string tr_um { get; set; }
        public Nullable<System.DateTime> tr_last_date { get; set; }
        public string tr_nbr { get; set; }
        public string tr_so_job { get; set; }
        public string tr_ship_type { get; set; }
        public string tr_addr { get; set; }
        public string tr_rmks { get; set; }
        public Nullable<decimal> tr_mtl_std { get; set; }
        public Nullable<decimal> tr_lbr_std { get; set; }
        public Nullable<decimal> tr_bdn_std { get; set; }
        public Nullable<decimal> tr_price { get; set; }
        public int tr_trnbr { get; set; }
        public Nullable<decimal> tr_gl_amt { get; set; }
        public string tr_lot { get; set; }
        public Nullable<decimal> tr_sub_std { get; set; }
        public Nullable<System.DateTime> tr_gl_date { get; set; }
        public Nullable<decimal> tr_qty_loc { get; set; }
        public string tr_userid { get; set; }
        public string tr_serial { get; set; }
        public string tr_prod_line { get; set; }
        public Nullable<int> tr_line { get; set; }
        public string tr_user1 { get; set; }
        public string tr_user2 { get; set; }
        public string tr_curr { get; set; }
        public Nullable<decimal> tr_ex_rate { get; set; }
        public string tr_rev { get; set; }
        public Nullable<int> tr_time { get; set; }
        public Nullable<decimal> tr_ovh_std { get; set; }
        public string tr_site { get; set; }
        public string tr_status { get; set; }
        public string tr_grade { get; set; }
        public Nullable<System.DateTime> tr_expire { get; set; }
        public Nullable<decimal> tr_assay { get; set; }
        public string tr_ref { get; set; }
        public Nullable<int> tr_msg { get; set; }
        public string tr_program { get; set; }
        public Nullable<int> tr_ord_rev { get; set; }
        public string tr_ref_site { get; set; }
        public string tr_for { get; set; }
        public string tr_rsn_code { get; set; }
        public string tr_daycode { get; set; }
        public Nullable<System.DateTime> tr_vend_date { get; set; }
        public string tr_vend_lot { get; set; }
        public string tr_slspsn { get; set; }
        public string tr_fsm_type { get; set; }
        public Nullable<bool> tr_upd_isb { get; set; }
        public Nullable<bool> tr_auto_install { get; set; }
        public string tr_ca_int_type { get; set; }
        public Nullable<decimal> tr_covered_amt { get; set; }
        public string tr_batch { get; set; }
        public Nullable<int> tr_wod_op { get; set; }
        public string tr_enduser { get; set; }
        public string tr_ship_inv_mov { get; set; }
        public Nullable<System.DateTime> tr_ship_date { get; set; }
        public string tr_ship_id { get; set; }
        public Nullable<System.DateTime> tr_promise_date { get; set; }
        public Nullable<System.DateTime> tr_effdate { get; set; }
        public Nullable<System.DateTime> tr__dte01 { get; set; }
    }
}
