//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tra_det
    {
        public int tra_id { get; set; }
        public int tra_recid { get; set; }
        public string tra_details { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
