//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class trgl_det
    {
        public string trgl_cr_acct { get; set; }
        public string trgl_cr_cc { get; set; }
        public string trgl_dr_acct { get; set; }
        public string trgl_dr_cc { get; set; }
        public Nullable<decimal> trgl_gl_amt { get; set; }
        public string trgl_gl_ref { get; set; }
        public int trgl_trnbr { get; set; }
        public string trgl_type { get; set; }
        public string trgl_cr_proj { get; set; }
        public string trgl_dr_proj { get; set; }
        public Nullable<int> trgl_cr_line { get; set; }
        public Nullable<int> trgl_dr_line { get; set; }
        public string trgl_user1 { get; set; }
        public string trgl_user2 { get; set; }
        public int trgl_sequence { get; set; }
        public string trgl__qadc01 { get; set; }
        public string trgl_dy_code { get; set; }
        public string trgl_dy_num { get; set; }
        public string trgl_cr_sub { get; set; }
        public string trgl_dr_sub { get; set; }
        public string trgl_domain { get; set; }
        public decimal oid_trgl_det { get; set; }
        public bool trgl_eff_trans { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
    }
}
