//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadQueue
    {
        public int ID { get; set; }
        public string SiteID { get; set; }
        public Nullable<int> SystemNo { get; set; }
        public Nullable<int> DeviceNo { get; set; }
        public string Description { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Department { get; set; }
        public string Member { get; set; }
        public Nullable<int> Status { get; set; }
        public string ReplyTo { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
