//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class usr_mstr
    {
        public string usr_userid { get; set; }
        public string usr_lang { get; set; }
        public string usr_user1 { get; set; }
        public string usr_user2 { get; set; }
        public string usr_site { get; set; }
        public string usr__qadc05 { get; set; }
        public string usr_passwd { get; set; }
        public string usr_name { get; set; }
        public Nullable<System.DateTime> usr_last_date { get; set; }
        public string usr__qad01 { get; set; }
        public string usr__qad02 { get; set; }
        public bool usr__qadl03 { get; set; }
        public string usr__qadc03 { get; set; }
        public string usr_addr { get; set; }
        public bool usr_restrict { get; set; }
        public string usr__qadc02 { get; set; }
        public Nullable<int> usr__qadi02 { get; set; }
        public string usr__qadc01 { get; set; }
        public Nullable<bool> usr__qadl01 { get; set; }
        public Nullable<bool> usr__qadl02 { get; set; }
        public string usr__qadc04 { get; set; }
        public Nullable<int> usr__qadi01 { get; set; }
        public string usr_mail_address { get; set; }
        public string usr_type { get; set; }
        public string usr_timezone { get; set; }
        public string usr_access_type { get; set; }
        public string usr_access_loc { get; set; }
        public string usr_ctry_code { get; set; }
        public string usr_variant_code { get; set; }
        public int usr_failed_attempts { get; set; }
        public bool usr_force_change { get; set; }
        public Nullable<System.DateTime> usr_logon_date { get; set; }
        public bool usr_active { get; set; }
        public string usr_active_by { get; set; }
        public string usr_active_reason { get; set; }
        public System.DateTime usr_active_date { get; set; }
        public string usr_logon_timezone { get; set; }
        public string usr_remark { get; set; }
        public int usr_logon_time { get; set; }
        public decimal oid_usr_mstr { get; set; }
        public string usr_tzdb { get; set; }
    }
}
