//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class usrgd_det
    {
        public string usrgd_userid { get; set; }
        public string usrgd_mod_userid { get; set; }
        public System.DateTime usrgd_mod_date { get; set; }
        public string usrgd_user1 { get; set; }
        public string usrgd_user2 { get; set; }
        public string usrgd__qadc01 { get; set; }
        public string usrgd__qadc02 { get; set; }
        public decimal oid_usrgd_det { get; set; }
        public decimal oid_usrg_mstr { get; set; }
        public string usrgd_domain { get; set; }
    }
}
