//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class usrg_mstr
    {
        public string usrg_group_name { get; set; }
        public string usrg_group_desc { get; set; }
        public string usrg_mod_userid { get; set; }
        public System.DateTime usrg_mod_date { get; set; }
        public string usrg_user1 { get; set; }
        public string usrg_user2 { get; set; }
        public string usrg__qadc01 { get; set; }
        public string usrg__qadc02 { get; set; }
        public decimal oid_usrg_mstr { get; set; }
    }
}
