//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vd_mstr1
    {
        public string vd_addr { get; set; }
        public string vd_cr_terms { get; set; }
        public string vd_buyer { get; set; }
        public Nullable<decimal> vd_disc_pct { get; set; }
        public string vd_shipvia { get; set; }
        public Nullable<bool> vd_partial { get; set; }
        public string vd_rmks { get; set; }
        public string vd_ap_acct { get; set; }
        public string vd_ap_cc { get; set; }
        public string vd_pur_acct { get; set; }
        public string vd_pur_cc { get; set; }
        public string vd_pur_cntct { get; set; }
        public string vd_ap_cntct { get; set; }
        public Nullable<bool> vd_1099 { get; set; }
        public string vd_sort { get; set; }
        public Nullable<System.DateTime> vd_last_ck { get; set; }
        public Nullable<decimal> vd_balance { get; set; }
        public Nullable<bool> vd_hold { get; set; }
        public string vd_tax_id { get; set; }
        public Nullable<bool> vd_taxable { get; set; }
        public string vd_user1 { get; set; }
        public string vd_user2 { get; set; }
        public string vd_curr { get; set; }
        public string vd_lang { get; set; }
        public string vd_vt_id { get; set; }
        public string vd__chr01 { get; set; }
        public string vd__chr02 { get; set; }
        public string vd__chr03 { get; set; }
        public string vd__chr04 { get; set; }
        public string vd__chr05 { get; set; }
        public string vd__chr06 { get; set; }
        public string vd__chr07 { get; set; }
        public string vd__chr08 { get; set; }
        public string vd__chr09 { get; set; }
        public string vd__chr10 { get; set; }
        public Nullable<System.DateTime> vd__dte01 { get; set; }
        public Nullable<System.DateTime> vd__dte02 { get; set; }
        public Nullable<decimal> vd__dec01 { get; set; }
        public Nullable<decimal> vd__dec02 { get; set; }
        public Nullable<bool> vd__log01 { get; set; }
        public string vd_fob { get; set; }
        public string vd_debtor { get; set; }
        public string vd_bank { get; set; }
        public string vd_ckfrm { get; set; }
        public Nullable<bool> vd_pay_spec { get; set; }
        public string vd_remit { get; set; }
        public string vd_type { get; set; }
        public string vd_userid { get; set; }
        public Nullable<System.DateTime> vd_mod_date { get; set; }
        public Nullable<decimal> vd_prepay { get; set; }
        public string vd_conrep_logic { get; set; }
        public string vd_pr_list { get; set; }
        public Nullable<decimal> vd_drft_bal { get; set; }
        public Nullable<decimal> vd_lc_bal { get; set; }
        public string vd_pr_list2 { get; set; }
        public Nullable<bool> vd_fix_pr { get; set; }
        public string vd_fr_list { get; set; }
        public Nullable<decimal> vd_fr_min_wt { get; set; }
        public string vd_fr_terms { get; set; }
        public string vd_tid_notice { get; set; }
        public string vd_promo { get; set; }
        public bool vd_misc_cr { get; set; }
        public bool vd_rcv_so_price { get; set; }
        public bool vd_rcv_held_so { get; set; }
        public bool vd_tp_use_pct { get; set; }
        public decimal vd_tp_pct { get; set; }
        public string vd_ex_ratetype { get; set; }
        public string vd_db { get; set; }
        public string vd__qadc01 { get; set; }
        public string vd__qadc02 { get; set; }
        public string vd__qadc03 { get; set; }
        public string vd__qadc04 { get; set; }
        public Nullable<decimal> vd__qadd01 { get; set; }
        public Nullable<decimal> vd__qadd02 { get; set; }
        public Nullable<bool> vd__qadl01 { get; set; }
        public Nullable<bool> vd__qadl02 { get; set; }
        public Nullable<System.DateTime> vd__qadt01 { get; set; }
        public Nullable<System.DateTime> vd__qadt02 { get; set; }
        public Nullable<int> vd__qadi01 { get; set; }
        public Nullable<int> vd__qadi02 { get; set; }
        public Nullable<bool> vd__qadl03 { get; set; }
        public Nullable<bool> vd__qadl04 { get; set; }
        public string vd_ap_sub { get; set; }
        public string vd_pur_sub { get; set; }
        public string vd_tot_terms_code { get; set; }
        public string vd_domain { get; set; }
        public decimal oid_vd_mstr { get; set; }
    }
}
