//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFormStatusWithSafetyAction
    {
        public int FormHeaderId { get; set; }
        public string Site { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public string CreatedByName { get; set; }
        public string CreatedByEmpNo { get; set; }
        public string ModifiedByName { get; set; }
        public string ModifiedByEmpNo { get; set; }
        public string CurrentOwnerName { get; set; }
        public string CurrentOwnerEmpNo { get; set; }
        public string FormType { get; set; }
        public string Title { get; set; }
        public string FormStatus { get; set; }
        public Nullable<int> SafetyActionId { get; set; }
        public string SATitle { get; set; }
        public Nullable<System.DateTime> SACreated { get; set; }
        public Nullable<System.DateTime> SAModified { get; set; }
        public Nullable<int> SASite { get; set; }
        public string SAModifiedByName { get; set; }
        public string SAModifiedByEmpNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string AssignedToName { get; set; }
        public string AssignedToEmpNo { get; set; }
        public Nullable<int> PercentageComplete { get; set; }
        public string MexNumber { get; set; }
        public string Description { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
    }
}
