//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vIncidentAccident
    {
        public int IncidentAccidentId { get; set; }
        public string Site { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public string CreatedByName { get; set; }
        public string CreatedByEmpNo { get; set; }
        public string ModifiedByName { get; set; }
        public string ModifiedByEmpNo { get; set; }
        public string CurrentOwnerName { get; set; }
        public string CurrentOwnerEmpNo { get; set; }
        public string FormType { get; set; }
        public string Title { get; set; }
        public string FormStatus { get; set; }
        public string IncidentAccidentFormType { get; set; }
        public string Employee { get; set; }
        public string Position { get; set; }
        public string EmploymentRelationship { get; set; }
        public string BusinessName { get; set; }
        public string ContactTelephoneNumber { get; set; }
        public System.DateTime DateOfIncidentAccident { get; set; }
        public System.DateTime TimeOfIncidentAccident { get; set; }
        public System.DateTime ShiftStartTime { get; set; }
        public string LocationOfIncidentAccident { get; set; }
        public System.DateTime DateReported { get; set; }
        public string ToWhom { get; set; }
        public string NameOfWitnessWitnesses { get; set; }
        public string WhatHappened { get; set; }
        public string Causes { get; set; }
        public string TreatmentDetails { get; set; }
        public string OtherTreatmentDetails { get; set; }
        public string FirstAidAdministered { get; set; }
        public string FollowUp { get; set; }
        public string HeathSafetyRepName { get; set; }
        public string InjurySeverity { get; set; }
        public string InjurySeverityOther { get; set; }
        public string FirstAider { get; set; }
        public string CauseOfIncident { get; set; }
    }
}
