//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vJseaRiskAssessments_
    {
        public int JseaRiskAssessmentId { get; set; }
        public string Site { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public string CreatedByName { get; set; }
        public string CreatedByEmpNo { get; set; }
        public string ModifiedByName { get; set; }
        public string ModifiedByEmpNo { get; set; }
        public string CurrentOwnerName { get; set; }
        public string CurrentOwnerEmpNo { get; set; }
        public string FormType { get; set; }
        public string Title { get; set; }
        public string FormStatus { get; set; }
        public System.DateTime TaskDate { get; set; }
        public string TaskLocation { get; set; }
        public System.DateTime TaskValidTill { get; set; }
        public string PersonResponsible { get; set; }
        public string PlantEquipmentUsed { get; set; }
        public string MaterialUsed { get; set; }
        public string Permit { get; set; }
        public string PermitNumber { get; set; }
        public string DetailsOfEquipment { get; set; }
        public string PrepByName { get; set; }
        public string PrepByPosition { get; set; }
        public string PrepByDate { get; set; }
        public string EnviroRevPrepByName { get; set; }
        public string EnviroRevPosition { get; set; }
        public string EnviroRevDate { get; set; }
        public string SafetyRevPrepByName { get; set; }
        public string SafetyRevPosition { get; set; }
        public string SafetyRevDate { get; set; }
        public string ApprovedPrepByName { get; set; }
        public string ApprovedByPosition { get; set; }
        public string ApprovedByDate { get; set; }
        public string JobStep { get; set; }
        public string PotentialRisksImpacts { get; set; }
        public string CurrentRiskRating { get; set; }
        public string ControlMeasures { get; set; }
        public string NewRiskRating { get; set; }
        public string PersonResponsibleEnsureImp { get; set; }
        public string SignOffName { get; set; }
        public System.DateTime SignOffDate { get; set; }
        public System.DateTime SignOffTime { get; set; }
        public string SignOffEmployer { get; set; }
        public string SignOffComments { get; set; }
        public string Activity { get; set; }
        public string ReviewPersonResponsible { get; set; }
        public Nullable<System.DateTime> ReviewDatePerformed { get; set; }
        public string ReviewFindings { get; set; }
        public string ReviewActionIfRequired { get; set; }
        public Nullable<System.DateTime> ReviewDateClosed { get; set; }
        public string ReviewClosedBy { get; set; }
    }
}
