//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vo_mstr
    {
        public string vo_ref { get; set; }
        public string vo_cr_terms { get; set; }
        public string vo_invoice { get; set; }
        public Nullable<decimal> vo_applied { get; set; }
        public Nullable<System.DateTime> vo_disc_date { get; set; }
        public Nullable<System.DateTime> vo_due_date { get; set; }
        public Nullable<bool> vo_hold { get; set; }
        public Nullable<System.DateTime> vo_paid_date { get; set; }
        public Nullable<decimal> vo_amt_chg { get; set; }
        public Nullable<decimal> vo_disc_chg { get; set; }
        public string vo_po { get; set; }
        public string vo_receiver { get; set; }
        public Nullable<decimal> vo_ndisc_amt { get; set; }
        public Nullable<decimal> vo_hold_amt { get; set; }
        public Nullable<int> vo_cmtindx { get; set; }
        public string vo_curr { get; set; }
        public Nullable<decimal> vo_ex_rate { get; set; }
        public string vo_user1 { get; set; }
        public Nullable<bool> vo_separate { get; set; }
        public string vo_ship { get; set; }
        public Nullable<bool> vo_confirmed { get; set; }
        public string vo_conf_by { get; set; }
        public decimal vo_base_applied { get; set; }
        public decimal vo_base_amt_chg { get; set; }
        public decimal vo_base_disc_chg { get; set; }
    }
}
