//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vod_det
    {
        public string vod_ref { get; set; }
        public string vod_acct { get; set; }
        public string vod_cc { get; set; }
        public string vod_project { get; set; }
        public string vod_desc { get; set; }
        public Nullable<decimal> vod_amt { get; set; }
        public int vod_ln { get; set; }
        public string vod_type { get; set; }
        public string vod_user1 { get; set; }
        public string vod_user2 { get; set; }
        public string vod_entity { get; set; }
        public string vod_tax_at { get; set; }
        public string vod_tax { get; set; }
        public string vod_tax_usage { get; set; }
        public string vod_taxc { get; set; }
        public string vod_exp_acct { get; set; }
        public string vod_exp_cc { get; set; }
        public string vod__qadc01 { get; set; }
        public Nullable<bool> vod_taxable { get; set; }
        public string vod_tax_env { get; set; }
        public Nullable<bool> vod_tax_in { get; set; }
        public string vod_dy_code { get; set; }
        public string vod_dy_num { get; set; }
        public decimal vod_base_amt { get; set; }
        public string vod_sub { get; set; }
        public string vod_exp_sub { get; set; }
        public int vod_pjs_line { get; set; }
    }
}
