//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vph_hist
    {
        public Nullable<decimal> vph_curr_amt { get; set; }
        public string vph_ref { get; set; }
        public string vph_nbr { get; set; }
        public Nullable<decimal> vph_inv_cost { get; set; }
        public Nullable<decimal> vph_inv_qty { get; set; }
        public Nullable<System.DateTime> vph_inv_date { get; set; }
        public Nullable<bool> vph_adj_inv { get; set; }
        public Nullable<bool> vph_adj_wip { get; set; }
        public Nullable<decimal> vph_adj_amt { get; set; }
        public Nullable<decimal> vph_dscr_amt { get; set; }
        public Nullable<decimal> vph_cf_adj_amt { get; set; }
        public Nullable<decimal> vph_cf_dscr_amt { get; set; }
        public Nullable<decimal> vph_adj_prv_cst { get; set; }
        public Nullable<decimal> vph_qoh_at_adj { get; set; }
        public int vph_pvo_id { get; set; }
        public int vph_pvod_id_line { get; set; }
    }
}
