//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRiskAssessment
    {
        public int RiskAssessmentId { get; set; }
        public string Site { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public string CreatedByName { get; set; }
        public string CreatedByEmpNo { get; set; }
        public string ModifiedByName { get; set; }
        public string ModifiedByEmpNo { get; set; }
        public string CurrentOwnerName { get; set; }
        public string CurrentOwnerEmpNo { get; set; }
        public string FormType { get; set; }
        public string Title { get; set; }
        public string FormStatus { get; set; }
        public string HowHazardProblemIdentified { get; set; }
        public string HowHazardProblemIdentifiedOther { get; set; }
        public string HazardManagementTeam { get; set; }
        public string IncidentReportNumber { get; set; }
        public string Location { get; set; }
        public string HazardBeingAssessed { get; set; }
        public System.DateTime DateOfAssessment { get; set; }
        public System.DateTime TimeOfAssessment { get; set; }
        public string AreaSection { get; set; }
        public string PartHistory { get; set; }
        public string SafetyHazardsEnvironmentalImpacts { get; set; }
        public string PotentialRisksImpacts { get; set; }
        public string CurrentControls { get; set; }
        public string CurrentRiskRating { get; set; }
        public string ControlsAdequate { get; set; }
        public string ProposedNewControls { get; set; }
        public string NewRiskRating { get; set; }
        public string ObservationNumber { get; set; }
    }
}
