//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSafetyActionsThisMonthByUser
    {
        public long SafetyActionsThisMonthByUserId { get; set; }
        public string CurrentOwnerName { get; set; }
        public string CurrentOwnerEmpNo { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
