//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAp_mstr_oldpo
    {
        public int voucherID { get; set; }
        public string voucherNumber { get; set; }
        public string supplierID { get; set; }
        public string invoiceNumber { get; set; }
        public string userComments { get; set; }
        public int status { get; set; }
        public bool PORequired { get; set; }
        public string userID { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
    }
}
