//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEntityCCAcc
    {
        public int EntityCCAccID { get; set; }
        public int EntityID { get; set; }
        public string Code { get; set; }
        public int CostCentreID { get; set; }
        public int CostCentreCode { get; set; }
        public int AccountID { get; set; }
        public string AccountCode { get; set; }
        public Nullable<int> SubAccountID { get; set; }
        public string SubAccountCode { get; set; }
    }
}
