//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class wc_mstr_manual
    {
        public string wc_wkctr { get; set; }
        public string wc_desc { get; set; }
        public string wc_dept { get; set; }
        public Nullable<decimal> wc_mch_wkctr { get; set; }
        public Nullable<int> wc_mch_op { get; set; }
        public Nullable<decimal> wc_men_mch { get; set; }
        public Nullable<decimal> wc_lbr_rate { get; set; }
        public Nullable<decimal> wc_bdn_rate { get; set; }
        public Nullable<decimal> wc_bdn_pct { get; set; }
        public Nullable<decimal> wc_mch_bdn { get; set; }
        public string wc_userid { get; set; }
        public Nullable<System.DateTime> wc_mod_date { get; set; }
        public string wc_domain { get; set; }
    }
}
