//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class wo_mstr
    {
        public string wo_nbr { get; set; }
        public string wo_lot { get; set; }
        public string wo_so_job { get; set; }
        public Nullable<System.DateTime> wo_ord_date { get; set; }
        public Nullable<System.DateTime> wo_rel_date { get; set; }
        public Nullable<System.DateTime> wo_due_date { get; set; }
        public Nullable<System.DateTime> wo_per_date { get; set; }
        public string wo_part { get; set; }
        public string wo_type { get; set; }
        public Nullable<decimal> wo_qty_ord { get; set; }
        public Nullable<decimal> wo_qty_comp { get; set; }
        public Nullable<decimal> wo_qty_rjct { get; set; }
        public string wo_status { get; set; }
        public string wo_vend { get; set; }
        public string wo_rmks { get; set; }
        public Nullable<decimal> wo_qty_chg { get; set; }
        public Nullable<decimal> wo_rjct_chg { get; set; }
        public Nullable<decimal> wo_bo_chg { get; set; }
        public Nullable<decimal> wo_yield_pct { get; set; }
        public string wo_rev { get; set; }
        public string wo_acct { get; set; }
        public string wo_cc { get; set; }
        public string wo_lot_prev { get; set; }
        public string wo_schd_type { get; set; }
        public Nullable<int> wo_cmtindx { get; set; }
        public string wo_project { get; set; }
        public Nullable<int> wo_lead_time { get; set; }
        public Nullable<decimal> wo_wip_tot { get; set; }
        public Nullable<decimal> wo_lbr_tot { get; set; }
        public Nullable<decimal> wo_mtl_tot { get; set; }
        public Nullable<decimal> wo_bdn_tot { get; set; }
        public Nullable<decimal> wo_sub_tot { get; set; }
        public string wo_user1 { get; set; }
        public string wo_user2 { get; set; }
        public Nullable<decimal> wo_ovh_tot { get; set; }
        public string wo_loc { get; set; }
        public string wo_serial { get; set; }
        public string wo_routing { get; set; }
        public string wo_bom_code { get; set; }
        public string wo_site { get; set; }
        public Nullable<decimal> wo_queue_eff { get; set; }
        public string wo_draw { get; set; }
        public Nullable<bool> wo_lbr_up { get; set; }
        public Nullable<bool> wo_bdn_up { get; set; }
        public Nullable<bool> wo_gl_lbr { get; set; }
        public Nullable<bool> wo_gl_bdn { get; set; }
        public string wo_line { get; set; }
        public Nullable<bool> wo_var { get; set; }
        public Nullable<decimal> wo_mtl_var { get; set; }
        public Nullable<decimal> wo_lbr_var { get; set; }
        public Nullable<decimal> wo_bdn_var { get; set; }
        public Nullable<decimal> wo_sub_var { get; set; }
        public string wo_mvar_acct { get; set; }
        public string wo_mvar_cc { get; set; }
        public string wo_mvrr_acct { get; set; }
        public string wo_mvrr_cc { get; set; }
        public string wo_svar_acct { get; set; }
        public string wo_svar_cc { get; set; }
        public string wo_svrr_acct { get; set; }
        public string wo_svrr_cc { get; set; }
        public string wo_flr_acct { get; set; }
        public string wo_flr_cc { get; set; }
        public Nullable<decimal> wo_rjct_tot { get; set; }
        public Nullable<decimal> wo_mthd_var { get; set; }
        public Nullable<decimal> wo_rval_tot { get; set; }
        public Nullable<bool> wo_acct_close { get; set; }
        public Nullable<System.DateTime> wo_close_date { get; set; }
        public Nullable<System.DateTime> wo_close_eff { get; set; }
        public string wo_fsm_type { get; set; }
        public string wo_xvar_acct { get; set; }
        public string wo_xvar_cc { get; set; }
        public decimal wo_myld_var { get; set; }
        public string wo_joint_type { get; set; }
        public Nullable<decimal> wo_prod_pct { get; set; }
        public string wo_qty_type { get; set; }
        public string wo_base_id { get; set; }
        public Nullable<decimal> wo_unit_cost { get; set; }
        public Nullable<decimal> wo_mix_var { get; set; }
        public Nullable<decimal> wo_bdn_totx { get; set; }
        public Nullable<decimal> wo_lbr_totx { get; set; }
        public Nullable<decimal> wo_mtl_totx { get; set; }
        public Nullable<decimal> wo_sub_totx { get; set; }
        public Nullable<decimal> wo_ovh_totx { get; set; }
        public string wo_batch { get; set; }
        public Nullable<decimal> wo_assay { get; set; }
        public string wo_grade { get; set; }
        public Nullable<System.DateTime> wo_expire { get; set; }
        public string wo_rctstat { get; set; }
        public string wo_lot_next { get; set; }
        public Nullable<bool> wo_lot_rcpt { get; set; }
        public Nullable<bool> wo_rctstat_active { get; set; }
        public string wo_ca_int_type { get; set; }
        public Nullable<System.DateTime> wo_date_posted { get; set; }
        public string wo_iss_site { get; set; }
        public Nullable<int> wo_itm_line { get; set; }
        public string wo_eng_code { get; set; }
        public string wo_sub { get; set; }
        public string wo_flr_sub { get; set; }
        public string wo_mvar_sub { get; set; }
        public string wo_mvrr_sub { get; set; }
        public string wo_svar_sub { get; set; }
        public string wo_svrr_sub { get; set; }
        public string wo_xvar_sub { get; set; }
        public string wo_ref { get; set; }
        public Nullable<System.DateTime> wo_record_date { get; set; }
        public Nullable<System.DateTime> wo_stat_close_date { get; set; }
        public string wo_stat_close_userid { get; set; }
    }
}
