//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class wod_det
    {
        public string wod_nbr { get; set; }
        public string wod_lot { get; set; }
        public Nullable<System.DateTime> wod_iss_date { get; set; }
        public string wod_part { get; set; }
        public Nullable<decimal> wod_qty_req { get; set; }
        public Nullable<decimal> wod_qty_all { get; set; }
        public Nullable<decimal> wod_qty_pick { get; set; }
        public Nullable<decimal> wod_qty_iss { get; set; }
        public Nullable<decimal> wod_tot_std { get; set; }
        public string wod_deliver { get; set; }
        public Nullable<decimal> wod_qty_chg { get; set; }
        public Nullable<decimal> wod_bo_chg { get; set; }
        public string wod_loc { get; set; }
        public string wod_serial { get; set; }
        public Nullable<int> wod_cmtindx { get; set; }
        public string wod_user1 { get; set; }
        public string wod_user2 { get; set; }
        public Nullable<int> wod_op { get; set; }
        public Nullable<bool> wod_critical { get; set; }
        public string wod_site { get; set; }
        public Nullable<decimal> wod_bom_qty { get; set; }
        public Nullable<decimal> wod_mtl_totx { get; set; }
        public Nullable<decimal> wod_mvuse_post { get; set; }
        public Nullable<decimal> wod_bom_amt { get; set; }
        public Nullable<decimal> wod_mvrte_post { get; set; }
        public Nullable<decimal> wod_mvrte_rval { get; set; }
        public Nullable<decimal> wod_mvuse_rval { get; set; }
        public Nullable<decimal> wod_mvrte_accr { get; set; }
        public Nullable<decimal> wod_mvuse_accr { get; set; }
        public string wod_ca_int_type { get; set; }
        public Nullable<decimal> wod_covered_amt { get; set; }
        public string wod_eng_code { get; set; }
        public string wod_fcg_code { get; set; }
        public Nullable<int> wod_fcg_index { get; set; }
        public Nullable<int> wod_fis_column { get; set; }
        public string wod_fis_sort { get; set; }
        public string wod_fsc_code { get; set; }
        public string wod_fsm_type { get; set; }
        public Nullable<decimal> wod_list_pr { get; set; }
        public Nullable<decimal> wod_price { get; set; }
        public string wod_prod_line { get; set; }
        public Nullable<decimal> wod_qty_posted { get; set; }
        public Nullable<decimal> wod_qty_ret { get; set; }
        public string wod_status { get; set; }
        public Nullable<decimal> wod_line_price { get; set; }
        public Nullable<decimal> wod_covered_post { get; set; }
        public string wod_project { get; set; }
        public Nullable<decimal> wod_ret_iss { get; set; }
        public Nullable<decimal> wod_exg_price { get; set; }
        public string wod_sv_code { get; set; }
        public string wod_ret_site { get; set; }
        public string wod_ret_loc { get; set; }
        public Nullable<decimal> wod_std_cost { get; set; }
        public Nullable<int> wod_itm_line { get; set; }
        public Nullable<int> wod_sod_line { get; set; }
        public string wod_sod_nbr { get; set; }
        public Nullable<bool> wod_seo_load { get; set; }
        public string wod_from_loc { get; set; }
        public string wod_from_site { get; set; }
        public string wod_ref { get; set; }
        public string wod_ret_serial { get; set; }
        public Nullable<int> wod_isb_ref { get; set; }
        public string wod_ret_ref { get; set; }
        public Nullable<decimal> wod_yield_pct { get; set; }
    }
}
