//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yield
    {
        public string Site { get; set; }
        public string Parent { get; set; }
        public string Component { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<double> YieldPercentage { get; set; }
        public Nullable<double> QuantityPer { get; set; }
        public Nullable<double> ScrapPercent { get; set; }
    }
}
