// <auto-generated />
namespace EPOv2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class level : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(level));
        
        string IMigrationMetadata.Id
        {
            get { return "201501160244130_level"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
