// <auto-generated />
namespace EPOv2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class custom51 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(custom51));
        
        string IMigrationMetadata.Id
        {
            get { return "201605030655441_custom51"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
