//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EPOv2.oneHarvestADSI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DirectorySoap", Namespace="http://tempuri.org/")]
    public partial class Directory : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetADInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSMTPEmailAddressesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDirectReportsByCNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersAndMembershipOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFullNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmailAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmailAddressByCNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserDetailsByCNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserDetailsByFullUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMembershipListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGroupMembersListOperationCompleted;
        
        private System.Threading.SendOrPostCallback isMemberOfV1OperationCompleted;
        
        private System.Threading.SendOrPostCallback isMemberOfOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupsAndMembersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Directory() {
            this.Url = global::EPOv2.Properties.Settings.Default.EPOv2_oneHarvestADSI_Directory;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetADInfoCompletedEventHandler GetADInfoCompleted;
        
        /// <remarks/>
        public event GetSMTPEmailAddressesCompletedEventHandler GetSMTPEmailAddressesCompleted;
        
        /// <remarks/>
        public event GetDirectReportsByCNCompletedEventHandler GetDirectReportsByCNCompleted;
        
        /// <remarks/>
        public event GetUsersAndMembershipCompletedEventHandler GetUsersAndMembershipCompleted;
        
        /// <remarks/>
        public event GetFullNameCompletedEventHandler GetFullNameCompleted;
        
        /// <remarks/>
        public event GetSiteCompletedEventHandler GetSiteCompleted;
        
        /// <remarks/>
        public event GetEmailAddressCompletedEventHandler GetEmailAddressCompleted;
        
        /// <remarks/>
        public event GetEmailAddressByCNCompletedEventHandler GetEmailAddressByCNCompleted;
        
        /// <remarks/>
        public event GetUserDetailsByCNCompletedEventHandler GetUserDetailsByCNCompleted;
        
        /// <remarks/>
        public event GetUserDetailsByFullUserNameCompletedEventHandler GetUserDetailsByFullUserNameCompleted;
        
        /// <remarks/>
        public event getMembershipListCompletedEventHandler getMembershipListCompleted;
        
        /// <remarks/>
        public event getGroupMembersListCompletedEventHandler getGroupMembersListCompleted;
        
        /// <remarks/>
        public event isMemberOfV1CompletedEventHandler isMemberOfV1Completed;
        
        /// <remarks/>
        public event isMemberOfCompletedEventHandler isMemberOfCompleted;
        
        /// <remarks/>
        public event GetGroupsAndMembersCompletedEventHandler GetGroupsAndMembersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetADInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetADInfo() {
            object[] results = this.Invoke("GetADInfo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetADInfoAsync() {
            this.GetADInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetADInfoAsync(object userState) {
            if ((this.GetADInfoOperationCompleted == null)) {
                this.GetADInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetADInfoOperationCompleted);
            }
            this.InvokeAsync("GetADInfo", new object[0], this.GetADInfoOperationCompleted, userState);
        }
        
        private void OnGetADInfoOperationCompleted(object arg) {
            if ((this.GetADInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetADInfoCompleted(this, new GetADInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSMTPEmailAddresses", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSMTPEmailAddresses() {
            object[] results = this.Invoke("GetSMTPEmailAddresses", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSMTPEmailAddressesAsync() {
            this.GetSMTPEmailAddressesAsync(null);
        }
        
        /// <remarks/>
        public void GetSMTPEmailAddressesAsync(object userState) {
            if ((this.GetSMTPEmailAddressesOperationCompleted == null)) {
                this.GetSMTPEmailAddressesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSMTPEmailAddressesOperationCompleted);
            }
            this.InvokeAsync("GetSMTPEmailAddresses", new object[0], this.GetSMTPEmailAddressesOperationCompleted, userState);
        }
        
        private void OnGetSMTPEmailAddressesOperationCompleted(object arg) {
            if ((this.GetSMTPEmailAddressesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSMTPEmailAddressesCompleted(this, new GetSMTPEmailAddressesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDirectReportsByCN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDirectReportsByCN(string CN) {
            object[] results = this.Invoke("GetDirectReportsByCN", new object[] {
                        CN});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDirectReportsByCNAsync(string CN) {
            this.GetDirectReportsByCNAsync(CN, null);
        }
        
        /// <remarks/>
        public void GetDirectReportsByCNAsync(string CN, object userState) {
            if ((this.GetDirectReportsByCNOperationCompleted == null)) {
                this.GetDirectReportsByCNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDirectReportsByCNOperationCompleted);
            }
            this.InvokeAsync("GetDirectReportsByCN", new object[] {
                        CN}, this.GetDirectReportsByCNOperationCompleted, userState);
        }
        
        private void OnGetDirectReportsByCNOperationCompleted(object arg) {
            if ((this.GetDirectReportsByCNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDirectReportsByCNCompleted(this, new GetDirectReportsByCNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsersAndMembership", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUsersAndMembership() {
            object[] results = this.Invoke("GetUsersAndMembership", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersAndMembershipAsync() {
            this.GetUsersAndMembershipAsync(null);
        }
        
        /// <remarks/>
        public void GetUsersAndMembershipAsync(object userState) {
            if ((this.GetUsersAndMembershipOperationCompleted == null)) {
                this.GetUsersAndMembershipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersAndMembershipOperationCompleted);
            }
            this.InvokeAsync("GetUsersAndMembership", new object[0], this.GetUsersAndMembershipOperationCompleted, userState);
        }
        
        private void OnGetUsersAndMembershipOperationCompleted(object arg) {
            if ((this.GetUsersAndMembershipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersAndMembershipCompleted(this, new GetUsersAndMembershipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFullName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFullName(string sFullUsername) {
            object[] results = this.Invoke("GetFullName", new object[] {
                        sFullUsername});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFullNameAsync(string sFullUsername) {
            this.GetFullNameAsync(sFullUsername, null);
        }
        
        /// <remarks/>
        public void GetFullNameAsync(string sFullUsername, object userState) {
            if ((this.GetFullNameOperationCompleted == null)) {
                this.GetFullNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullNameOperationCompleted);
            }
            this.InvokeAsync("GetFullName", new object[] {
                        sFullUsername}, this.GetFullNameOperationCompleted, userState);
        }
        
        private void OnGetFullNameOperationCompleted(object arg) {
            if ((this.GetFullNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullNameCompleted(this, new GetFullNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSite(string sFullUsername) {
            object[] results = this.Invoke("GetSite", new object[] {
                        sFullUsername});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSiteAsync(string sFullUsername) {
            this.GetSiteAsync(sFullUsername, null);
        }
        
        /// <remarks/>
        public void GetSiteAsync(string sFullUsername, object userState) {
            if ((this.GetSiteOperationCompleted == null)) {
                this.GetSiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSiteOperationCompleted);
            }
            this.InvokeAsync("GetSite", new object[] {
                        sFullUsername}, this.GetSiteOperationCompleted, userState);
        }
        
        private void OnGetSiteOperationCompleted(object arg) {
            if ((this.GetSiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSiteCompleted(this, new GetSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmailAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmailAddress(string sFullUsername) {
            object[] results = this.Invoke("GetEmailAddress", new object[] {
                        sFullUsername});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmailAddressAsync(string sFullUsername) {
            this.GetEmailAddressAsync(sFullUsername, null);
        }
        
        /// <remarks/>
        public void GetEmailAddressAsync(string sFullUsername, object userState) {
            if ((this.GetEmailAddressOperationCompleted == null)) {
                this.GetEmailAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmailAddressOperationCompleted);
            }
            this.InvokeAsync("GetEmailAddress", new object[] {
                        sFullUsername}, this.GetEmailAddressOperationCompleted, userState);
        }
        
        private void OnGetEmailAddressOperationCompleted(object arg) {
            if ((this.GetEmailAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmailAddressCompleted(this, new GetEmailAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmailAddressByCN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmailAddressByCN(string CN) {
            object[] results = this.Invoke("GetEmailAddressByCN", new object[] {
                        CN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmailAddressByCNAsync(string CN) {
            this.GetEmailAddressByCNAsync(CN, null);
        }
        
        /// <remarks/>
        public void GetEmailAddressByCNAsync(string CN, object userState) {
            if ((this.GetEmailAddressByCNOperationCompleted == null)) {
                this.GetEmailAddressByCNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmailAddressByCNOperationCompleted);
            }
            this.InvokeAsync("GetEmailAddressByCN", new object[] {
                        CN}, this.GetEmailAddressByCNOperationCompleted, userState);
        }
        
        private void OnGetEmailAddressByCNOperationCompleted(object arg) {
            if ((this.GetEmailAddressByCNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmailAddressByCNCompleted(this, new GetEmailAddressByCNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserDetailsByCN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserDetailsByCN(string CN) {
            object[] results = this.Invoke("GetUserDetailsByCN", new object[] {
                        CN});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserDetailsByCNAsync(string CN) {
            this.GetUserDetailsByCNAsync(CN, null);
        }
        
        /// <remarks/>
        public void GetUserDetailsByCNAsync(string CN, object userState) {
            if ((this.GetUserDetailsByCNOperationCompleted == null)) {
                this.GetUserDetailsByCNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserDetailsByCNOperationCompleted);
            }
            this.InvokeAsync("GetUserDetailsByCN", new object[] {
                        CN}, this.GetUserDetailsByCNOperationCompleted, userState);
        }
        
        private void OnGetUserDetailsByCNOperationCompleted(object arg) {
            if ((this.GetUserDetailsByCNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserDetailsByCNCompleted(this, new GetUserDetailsByCNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserDetailsByFullUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserDetailsByFullUserName(string SamAccountNameWithDomain) {
            object[] results = this.Invoke("GetUserDetailsByFullUserName", new object[] {
                        SamAccountNameWithDomain});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserDetailsByFullUserNameAsync(string SamAccountNameWithDomain) {
            this.GetUserDetailsByFullUserNameAsync(SamAccountNameWithDomain, null);
        }
        
        /// <remarks/>
        public void GetUserDetailsByFullUserNameAsync(string SamAccountNameWithDomain, object userState) {
            if ((this.GetUserDetailsByFullUserNameOperationCompleted == null)) {
                this.GetUserDetailsByFullUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserDetailsByFullUserNameOperationCompleted);
            }
            this.InvokeAsync("GetUserDetailsByFullUserName", new object[] {
                        SamAccountNameWithDomain}, this.GetUserDetailsByFullUserNameOperationCompleted, userState);
        }
        
        private void OnGetUserDetailsByFullUserNameOperationCompleted(object arg) {
            if ((this.GetUserDetailsByFullUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserDetailsByFullUserNameCompleted(this, new GetUserDetailsByFullUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMembershipList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getMembershipList(string sFullUserName) {
            object[] results = this.Invoke("getMembershipList", new object[] {
                        sFullUserName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getMembershipListAsync(string sFullUserName) {
            this.getMembershipListAsync(sFullUserName, null);
        }
        
        /// <remarks/>
        public void getMembershipListAsync(string sFullUserName, object userState) {
            if ((this.getMembershipListOperationCompleted == null)) {
                this.getMembershipListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMembershipListOperationCompleted);
            }
            this.InvokeAsync("getMembershipList", new object[] {
                        sFullUserName}, this.getMembershipListOperationCompleted, userState);
        }
        
        private void OngetMembershipListOperationCompleted(object arg) {
            if ((this.getMembershipListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMembershipListCompleted(this, new getMembershipListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getGroupMembersList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getGroupMembersList(string Membership) {
            object[] results = this.Invoke("getGroupMembersList", new object[] {
                        Membership});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getGroupMembersListAsync(string Membership) {
            this.getGroupMembersListAsync(Membership, null);
        }
        
        /// <remarks/>
        public void getGroupMembersListAsync(string Membership, object userState) {
            if ((this.getGroupMembersListOperationCompleted == null)) {
                this.getGroupMembersListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGroupMembersListOperationCompleted);
            }
            this.InvokeAsync("getGroupMembersList", new object[] {
                        Membership}, this.getGroupMembersListOperationCompleted, userState);
        }
        
        private void OngetGroupMembersListOperationCompleted(object arg) {
            if ((this.getGroupMembersListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGroupMembersListCompleted(this, new getGroupMembersListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isMemberOfV1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool isMemberOfV1(string sFullUserName, string sMembership) {
            object[] results = this.Invoke("isMemberOfV1", new object[] {
                        sFullUserName,
                        sMembership});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void isMemberOfV1Async(string sFullUserName, string sMembership) {
            this.isMemberOfV1Async(sFullUserName, sMembership, null);
        }
        
        /// <remarks/>
        public void isMemberOfV1Async(string sFullUserName, string sMembership, object userState) {
            if ((this.isMemberOfV1OperationCompleted == null)) {
                this.isMemberOfV1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnisMemberOfV1OperationCompleted);
            }
            this.InvokeAsync("isMemberOfV1", new object[] {
                        sFullUserName,
                        sMembership}, this.isMemberOfV1OperationCompleted, userState);
        }
        
        private void OnisMemberOfV1OperationCompleted(object arg) {
            if ((this.isMemberOfV1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isMemberOfV1Completed(this, new isMemberOfV1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isMemberOf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool isMemberOf(string sFullUserName, string sMembership) {
            object[] results = this.Invoke("isMemberOf", new object[] {
                        sFullUserName,
                        sMembership});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void isMemberOfAsync(string sFullUserName, string sMembership) {
            this.isMemberOfAsync(sFullUserName, sMembership, null);
        }
        
        /// <remarks/>
        public void isMemberOfAsync(string sFullUserName, string sMembership, object userState) {
            if ((this.isMemberOfOperationCompleted == null)) {
                this.isMemberOfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisMemberOfOperationCompleted);
            }
            this.InvokeAsync("isMemberOf", new object[] {
                        sFullUserName,
                        sMembership}, this.isMemberOfOperationCompleted, userState);
        }
        
        private void OnisMemberOfOperationCompleted(object arg) {
            if ((this.isMemberOfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isMemberOfCompleted(this, new isMemberOfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupsAndMembers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetGroupsAndMembers() {
            object[] results = this.Invoke("GetGroupsAndMembers", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupsAndMembersAsync() {
            this.GetGroupsAndMembersAsync(null);
        }
        
        /// <remarks/>
        public void GetGroupsAndMembersAsync(object userState) {
            if ((this.GetGroupsAndMembersOperationCompleted == null)) {
                this.GetGroupsAndMembersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupsAndMembersOperationCompleted);
            }
            this.InvokeAsync("GetGroupsAndMembers", new object[0], this.GetGroupsAndMembersOperationCompleted, userState);
        }
        
        private void OnGetGroupsAndMembersOperationCompleted(object arg) {
            if ((this.GetGroupsAndMembersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupsAndMembersCompleted(this, new GetGroupsAndMembersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetADInfoCompletedEventHandler(object sender, GetADInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetADInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetADInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetSMTPEmailAddressesCompletedEventHandler(object sender, GetSMTPEmailAddressesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSMTPEmailAddressesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSMTPEmailAddressesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetDirectReportsByCNCompletedEventHandler(object sender, GetDirectReportsByCNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDirectReportsByCNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDirectReportsByCNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUsersAndMembershipCompletedEventHandler(object sender, GetUsersAndMembershipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersAndMembershipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersAndMembershipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetFullNameCompletedEventHandler(object sender, GetFullNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetSiteCompletedEventHandler(object sender, GetSiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetEmailAddressCompletedEventHandler(object sender, GetEmailAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmailAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmailAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetEmailAddressByCNCompletedEventHandler(object sender, GetEmailAddressByCNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmailAddressByCNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmailAddressByCNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUserDetailsByCNCompletedEventHandler(object sender, GetUserDetailsByCNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserDetailsByCNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserDetailsByCNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUserDetailsByFullUserNameCompletedEventHandler(object sender, GetUserDetailsByFullUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserDetailsByFullUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserDetailsByFullUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void getMembershipListCompletedEventHandler(object sender, getMembershipListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMembershipListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMembershipListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void getGroupMembersListCompletedEventHandler(object sender, getGroupMembersListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGroupMembersListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGroupMembersListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void isMemberOfV1CompletedEventHandler(object sender, isMemberOfV1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isMemberOfV1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isMemberOfV1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void isMemberOfCompletedEventHandler(object sender, isMemberOfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isMemberOfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isMemberOfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetGroupsAndMembersCompletedEventHandler(object sender, GetGroupsAndMembersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupsAndMembersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupsAndMembersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591